import { loggerFactory, RedstoneCommon } from "@redstone-finance/utils";
import _ from "lodash";
import { performance } from "perf_hooks";
import {
  DefaultService,
  DisclosedContract,
  JsCantonError,
  OpenAPI,
  TransactionFormat,
} from "../_autogenerated";
import type { ApiRequestOptions } from "../_autogenerated/core/ApiRequestOptions";
import { CantonNetwork } from "../CantonNetwork";
import * as AllDefs from "../contracts.json";
import {
  extractCreatedEvents,
  extractExercisedResultsFromEvents,
  extractUpdateMetadata,
} from "../utils/extract-utils";
import { ContractFilter, CreatedArgumentCallback } from "../utils/price-feed-utils";
import {
  isJsActiveContract,
  makeActiveContractData,
  makeInterfaceFilterByParty,
  unwrapResponse,
} from "../utils/utils";
import { CantonScanApiClient } from "./CantonScanApiClient";

const DEFAULT_DELTA_OFFSET = 1000;
const LOCAL_USER = "redstone-canton-connector";
const MAX_RESPONSE_LIMIT = 200;

export interface TransactionMetadata {
  paidTrafficCost?: number;
}

export class CantonClient {
  private readonly logger = loggerFactory("canton-client");

  Defs: (typeof AllDefs)["devnet"];
  scanApiClient: CantonScanApiClient;

  constructor(
    private readonly baseUrl: string,
    network: CantonNetwork = "devnet",
    private readonly tokenProvider?: (options: ApiRequestOptions) => Promise<string>
  ) {
    this.Defs = AllDefs[network];

    this.scanApiClient = new CantonScanApiClient(
      baseUrl.split("/participants")[0] + "/http-proxy",
      network,
      tokenProvider
    );
  }

  async getCurrentOffset() {
    return (await this.performRequest(DefaultService.getV2StateLedgerEnd, "getCurrentOffset"))
      .offset;
  }

  async getTotalConsumedTraffic() {
    const status = await this.scanApiClient.getTrafficStatus();

    return status.traffic_status.actual.total_consumed;
  }

  async getRemainingTraffic() {
    const status = await this.scanApiClient.getTrafficStatus();
    const actual = status.traffic_status.actual;

    return actual.total_limit - actual.total_consumed;
  }

  private async fetchActiveContracts(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    limit = MAX_RESPONSE_LIMIT
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const filterDesc = Object.entries(filtersByParty)
      .map(
        ([partyId, filters]) =>
          `${partyId}:${filters.cumulative?.map((filter) => RedstoneCommon.stringify(filter.identifierFilter)).join(",")}`
      )
      .join(",");

    const contracts = await this.performRequest(
      () =>
        DefaultService.postV2StateActiveContracts(
          {
            filter: { filtersByParty },
            activeAtOffset: offset,
            verbose: false,
          },
          limit
        ),
      `postV2StateActiveContracts ${filterDesc}`
    );

    return contracts
      .filter(isJsActiveContract)
      .filter(
        (contract) =>
          !filter ||
          filter(
            contract.contractEntry.JsActiveContract.createdEvent.createArgument,
            contract.contractEntry.JsActiveContract.createdEvent.signatories
          )
      );
  }

  async getActiveContractsData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    limit = MAX_RESPONSE_LIMIT
  ) {
    return await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset, limit);
  }

  async getActiveContractWithPayload<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number
  ) {
    const adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    const [adapter, ...rest] = adapters;
    if (rest.length > 0) {
      throw new Error(`Unable to determine contract data of ${adapters.length} contracts`);
    }

    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return {
      ...makeActiveContractData(createdEvent, synchronizerId),
      createArgument: createdEvent.createArgument as T,
    };
  }

  async getActiveContractData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number
  ) {
    const adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    const [adapter, ...rest] = adapters;
    if (rest.length > 0) {
      throw new Error(`Unable to determine contract data of ${adapters.length} contracts`);
    }

    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return makeActiveContractData(createdEvent, synchronizerId);
  }

  async getMostActiveContractWithPayload<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    sorter?: CreatedArgumentCallback
  ) {
    let adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    if (sorter) {
      adapters = _.sortBy(adapters, (contract) =>
        sorter(
          contract.contractEntry.JsActiveContract.createdEvent.createArgument,
          contract.contractEntry.JsActiveContract.createdEvent.signatories
        )
      );
    }

    const [adapter] = adapters;
    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return {
      ...makeActiveContractData(createdEvent, synchronizerId),
      createArgument: createdEvent.createArgument as T,
    };
  }

  async getMostActiveContractData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    sorter?: CreatedArgumentCallback
  ) {
    const { createArgument: _, ...contractData } = await this.getMostActiveContractWithPayload(
      actAs,
      interfaceId,
      filter,
      atOffset,
      sorter
    );

    return contractData;
  }

  async getCreateContractEvents(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    deltaOffset = DEFAULT_DELTA_OFFSET,
    excludeArchived = false
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const contracts = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, offset - deltaOffset),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_ACS_DELTA
    );

    return extractCreatedEvents(contracts, filter, excludeArchived);
  }

  async getTransactionsForInterface(
    actAs: string,
    interfaceId: string,
    from: number,
    to: number,
    method: string
  ) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const result = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, from),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
      to
    );

    const updates = [];

    for (const { update } of result) {
      if (!("Transaction" in update)) {
        continue;
      }

      const updateId = update.Transaction.value.updateId;
      const fullUpdate = await this.performRequest(
        () =>
          DefaultService.postV2UpdatesUpdateById({
            updateId,
            updateFormat: {
              includeTransactions: {
                transactionShape:
                  TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
                eventFormat: {
                  filtersByParty: { [actAs]: {} },
                  verbose: false,
                },
              },
            },
          }),
        `getUpdates[updateId=${updateId}]`
      );

      const allEvents =
        "update" in fullUpdate && "Transaction" in fullUpdate.update
          ? (fullUpdate.update.Transaction.value.events ?? [])
          : [];

      const extracted = extractUpdateMetadata(allEvents, update.Transaction, method);

      updates.push(...extracted);
    }

    return updates;
  }

  async exerciseChoice<Arg extends object, Res = object>(
    actAs: string,
    command: { templateId: string; contractId: string; choice: string; choiceArgument: Arg },
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const { results, metadata } = await this.exerciseChoices<Arg, Res>(
      actAs,
      [command],
      timestamp,
      disclosedContracts
    );
    const [result] = Object.values(results);

    if (!result) {
      throw new Error(`No result for choice ${command.choice} on contract ${command.contractId}`);
    }

    return { result, metadata };
  }

  async exerciseChoicesWithoutWaiting<Arg extends object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");
    const commandId = CantonClient.getCommandId(choices, commands, timestamp);

    await this.performRequest(
      () =>
        DefaultService.postV2CommandsAsyncSubmit({
          commands: commands.map((command) => ({ ExerciseCommand: command })),
          commandId,
          actAs: [actAs],
          disclosedContracts,
          userId: !this.tokenProvider ? LOCAL_USER : undefined,
        }),
      `postV2CommandsAsyncSubmit ${CantonClient.describeCommandBatch(commands)}`
    );

    return commandId;
  }

  async exerciseChoices<Arg extends object, Res = object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");
    const commandId = CantonClient.getCommandId(choices, commands, timestamp);

    const result = await this.performRequest(
      () => {
        return DefaultService.postV2CommandsSubmitAndWaitForTransaction({
          commands: {
            commands: commands.map((command) => ({ ExerciseCommand: command })),
            commandId,
            actAs: [actAs],
            disclosedContracts,
            userId: !this.tokenProvider ? LOCAL_USER : undefined,
          },
          transactionFormat: {
            transactionShape: TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
            eventFormat: {
              filtersByParty: { [actAs]: {} },
              verbose: false,
            },
          },
        });
      },
      `postV2CommandsSubmitAndWaitForTransaction ${CantonClient.describeCommandBatch(commands)}`
    );

    const { events, synchronizerId, paidTrafficCost } = result.transaction;
    if (!RedstoneCommon.isDefined(events)) {
      throw new Error(`field events undefined even though explicitly requested`);
    }
    const results = extractExercisedResultsFromEvents<Res>(events, synchronizerId);

    return { results, metadata: { paidTrafficCost } as TransactionMetadata };
  }

  private async resolveFilterAndOffset(actAs: string, interfaceId: string, atOffset?: number) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const offset = atOffset ?? (await this.getCurrentOffset());

    return { filtersByParty, offset };
  }

  private async fetchUpdates(
    filtersByParty: Record<string, object>,
    beginExclusive: number,
    transactionShape: TransactionFormat.transactionShape,
    endInclusive?: number
  ) {
    return await this.performRequest(
      () =>
        DefaultService.postV2Updates({
          beginExclusive,
          endInclusive,
          verbose: false,
          updateFormat: {
            includeTransactions: {
              eventFormat: { filtersByParty, verbose: false },
              transactionShape,
            },
          },
        }),
      `postV2Updates ${RedstoneCommon.stringify(filtersByParty)}`
    );
  }

  private async performRequest<T>(
    promise: () => Promise<T | JsCantonError>,
    fnName = "performRequest"
  ) {
    OpenAPI.BASE = this.baseUrl;
    OpenAPI.TOKEN = this.tokenProvider;

    this.logger.info(`Calling ${fnName}`);

    return await unwrapResponse(this.logPerf(promise, fnName));
  }

  private async logPerf<T>(fn: () => Promise<T>, label: string): Promise<T> {
    const startTime = performance.now();
    try {
      return await fn();
    } finally {
      const duration = performance.now() - startTime;
      this.logger.info(`${label}: ${duration}[ms]`, { duration });
    }
  }

  private static getCommandId(choices: string, commands: unknown[], timestamp: Date) {
    return `batch-${choices}-${commands.length}-${timestamp.getTime()}-${Math.random().toFixed(4).substring(2)}`;
  }

  private static describeCommandBatch<Arg>(
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[]
  ) {
    const commandDesc = commands
      .map(({ contractId, choice }) => `${contractId}:${choice}`)
      .join(", ");

    return `batch[${commands.length}] (${commandDesc})`;
  }
}
