import { TokenStandardService } from "@canton-network/core-token-standard-service";
import { LedgerProvider, SDK, type SDKInterface } from "@canton-network/wallet-sdk";
import { decodeJwt } from "jose";
import { DefaultService, OpenAPI, type Command, type DisclosedContract } from "../_autogenerated";
import { unwrapResponse } from "../utils/utils";

export type CantonTransferServiceConfig = {
  ledgerJsonApiUrl: string;
  validatorApiUrl: string;
  getLedgerToken: () => Promise<string>;
  getWalletToken: () => Promise<string>;
};

export class CantonTransferService {
  private readonly sdkPromise: Promise<SDKInterface<never>>;
  private readonly ledgerProvider: LedgerProvider;
  private readonly tokenStandardRegistryUrl: string;

  constructor(private readonly cfg: CantonTransferServiceConfig) {
    this.tokenStandardRegistryUrl = `${cfg.validatorApiUrl}/v0/scan-proxy`;
    const getLedgerToken = cfg.getLedgerToken;

    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-assignment -- LedgerProvider re-exported from core-provider-ledger; type resolution fails under nodenext CJS/ESM boundary
    this.ledgerProvider = new LedgerProvider({
      baseUrl: cfg.ledgerJsonApiUrl,
      accessTokenProvider: {
        getAccessToken: () => getLedgerToken(),
        getAuthContext: async () => {
          const token = await getLedgerToken();
          const { sub } = decodeJwt(token);

          if (!sub) {
            throw new Error("JWT token is missing 'sub' claim");
          }

          return { userId: sub, accessToken: token };
        },
      },
    });

    this.sdkPromise = SDK.create({
      ledgerProvider: this.ledgerProvider as never,
    }) as unknown as Promise<SDKInterface<never>>;
  }

  async prepareTransfer(sender: string, recipient: string, amount: number) {
    const getWalletToken = this.cfg.getWalletToken;
    const sdk = await this.sdkPromise;

    const walletTokenProvider = {
      getAccessToken: () => getWalletToken(),
      getAuthContext: async () => {
        const token = await getWalletToken();
        const { sub } = decodeJwt(token);

        if (!sub) {
          throw new Error("JWT token is missing 'sub' claim");
        }

        return { userId: sub, accessToken: token };
      },
    };

    const tokenStandardService = new TokenStandardService(
      this.ledgerProvider,
      console,
      walletTokenProvider,
      false
    );

    const assets = await tokenStandardService.registriesToAssets([this.tokenStandardRegistryUrl]);
    const asset = assets.find((a) => a.id === "Amulet");

    if (!asset) {
      throw new Error(`Amulet asset not found in registry ${this.tokenStandardRegistryUrl}`);
    }

    const [rawCommand, disclosedContracts] = await tokenStandardService.transfer.createTransfer(
      sender,
      recipient,
      amount.toString(),
      asset.admin,
      asset.id,
      asset.registryUrl
    );

    return { sdk, transferCommand: { ExerciseCommand: rawCommand }, disclosedContracts };
  }

  async sendAmulet(
    actAs: string,
    recipient: string,
    amount: number
  ): Promise<{ updateId: string }> {
    const { transferCommand, disclosedContracts } = await this.prepareTransfer(
      actAs,
      recipient,
      amount
    );

    OpenAPI.BASE = this.cfg.ledgerJsonApiUrl;
    OpenAPI.TOKEN = this.cfg.getLedgerToken;

    return (await unwrapResponse(
      DefaultService.postV2CommandsSubmitAndWait({
        commands: [transferCommand] as Command[],
        commandId: `send-amulet-${Date.now()}`,
        actAs: [actAs],
        disclosedContracts: disclosedContracts as DisclosedContract[],
      })
    )) as { updateId: string };
  }
}
