import { TokenStandardService } from "@canton-network/core-token-standard-service";
import { LedgerProvider, SDK, type SDKInterface } from "@canton-network/wallet-sdk";
import { loggerFactory } from "@redstone-finance/utils";
import { sign } from "node:crypto";
import { DefaultService, OpenAPI } from "../_autogenerated";
import { makeEd25519PrivateKey } from "../utils/ed25519";
import { decodeJwtPayload, unwrapResponse } from "../utils/utils";

const logger = loggerFactory("canton-transfer");

export type TransferSigner = { partyId: string; privateKeyHex: string };

export type CantonTransferServiceConfig = {
  ledgerJsonApiUrl: string;
  validatorApiUrl: string;
  getLedgerToken: () => Promise<string>;
  getWalletToken: () => Promise<string>;
};

export class CantonTransferService {
  private readonly sdkPromise: Promise<SDKInterface>;
  private readonly ledgerProvider: LedgerProvider;
  private readonly tokenStandardRegistryUrl: string;

  constructor(private readonly cfg: CantonTransferServiceConfig) {
    this.tokenStandardRegistryUrl = `${cfg.validatorApiUrl}/v0/scan-proxy`;
    const getLedgerToken = cfg.getLedgerToken;

    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-assignment -- LedgerProvider re-exported from core-provider-ledger; type resolution fails under nodenext CJS/ESM boundary
    this.ledgerProvider = new LedgerProvider({
      baseUrl: cfg.ledgerJsonApiUrl,
      accessTokenProvider: {
        getAccessToken: () => getLedgerToken(),
        getAuthContext: async () => {
          const token = await getLedgerToken();
          const { sub } = decodeJwtPayload<{ sub?: string }>(token);

          if (!sub) {
            throw new Error("JWT token is missing 'sub' claim");
          }

          return { userId: sub, accessToken: token };
        },
      },
    });

    this.sdkPromise = SDK.create({
      ledgerProvider: this.ledgerProvider as never,
      logAdapter: "console",
    });
  }

  async transfer(toAddress: string, amount: number, signer: TransferSigner) {
    const { partyId } = signer;
    const privateKey = makeEd25519PrivateKey(signer.privateKeyHex);

    logger.log(`token-standard transfer: sender=${partyId} receiver=${toAddress} amount=${amount}`);

    const { sdk, transferCommand, disclosedContracts } = await this.prepareTransfer(
      partyId,
      toAddress,
      amount
    );

    const preparedTx = sdk.ledger.prepare({
      partyId,
      commands: transferCommand,
      disclosedContracts,
    });

    const { response } = await preparedTx.toJSON();
    logger.log(`prepare ok, hash=${response.preparedTransactionHash}`);

    const hashBytes = Buffer.from(response.preparedTransactionHash, "base64");
    const signatureBase64 = sign(null, hashBytes, privateKey).toString("base64");

    const signedTx = sdk.ledger.fromSignature(response, signatureBase64);
    const result = await signedTx.execute({ partyId });

    logger.log(`execute ok, updateId=${result.updateId} offset=${result.completionOffset}`);
  }

  private async prepareTransfer(sender: string, recipient: string, amount: number) {
    const getWalletToken = this.cfg.getWalletToken;
    const sdk = await this.sdkPromise;

    const walletTokenProvider = {
      getAccessToken: () => getWalletToken(),
      getAuthContext: async () => {
        const token = await getWalletToken();
        const { sub } = decodeJwtPayload<{ sub?: string }>(token);

        if (!sub) {
          throw new Error("JWT token is missing 'sub' claim");
        }

        return { userId: sub, accessToken: token };
      },
    };

    const tokenStandardService = new TokenStandardService(
      this.ledgerProvider,
      console,
      walletTokenProvider,
      false
    );

    const assets = await tokenStandardService.registriesToAssets([this.tokenStandardRegistryUrl]);
    const asset = assets.find((a) => a.id === "Amulet");

    if (!asset) {
      throw new Error(`Amulet asset not found in registry ${this.tokenStandardRegistryUrl}`);
    }

    const [rawCommand, disclosedContracts] = await tokenStandardService.transfer.createTransfer(
      sender,
      recipient,
      amount.toString(),
      asset.admin,
      asset.id,
      asset.registryUrl
    );

    return { sdk, transferCommand: { ExerciseCommand: rawCommand }, disclosedContracts };
  }

  async sendAmulet(actAs: string, recipient: string, amount: number) {
    const { transferCommand, disclosedContracts } = await this.prepareTransfer(
      actAs,
      recipient,
      amount
    );

    OpenAPI.BASE = this.cfg.ledgerJsonApiUrl;
    OpenAPI.TOKEN = this.cfg.getLedgerToken;

    return await unwrapResponse(
      DefaultService.postV2CommandsSubmitAndWait({
        commands: [transferCommand],
        commandId: `send-amulet-${Date.now()}`,
        actAs: [actAs],
        disclosedContracts,
      })
    );
  }
}
