import { RedstoneCommon } from "@redstone-finance/utils";
import _ from "lodash";
import {
  AllocateExternalPartyRequest,
  DefaultService,
  DisclosedContract,
  GenerateExternalPartyTopologyRequest,
  JsCantonError,
  OpenAPI,
  TransactionFormat,
} from "../_autogenerated";
import * as AllDefs from "../canton-defs.json";
import { CantonNetwork } from "../CantonNetwork";
import {
  extractCreatedEvents,
  extractExercisedResultsFromEvents,
  extractUpdateMetadata,
} from "../utils/extract-utils";
import { ContractFilter, CreatedArgumentCallback } from "../utils/price-feed-utils";
import {
  isJsActiveContract,
  makeActiveContractData,
  makeInterfaceFilterByParty,
  unwrapResponse,
} from "../utils/utils";
import { CantonApi } from "./CantonApi";
import { CantonScanApiClient, ScanCantonApi } from "./CantonScanApiClient";

const DEFAULT_DELTA_OFFSET = 1000;
const LOCAL_USER = "redstone-canton-connector";
const MAX_RESPONSE_LIMIT = 200;

export interface TransactionMetadata {
  paidTrafficCost?: number;
}

export class CantonClient {
  scanApiClient?: CantonScanApiClient;

  constructor(
    private readonly api: JsonCantonApi,
    public network: CantonNetwork = "devnet",
    scanApi?: ScanCantonApi
  ) {
    this.scanApiClient = scanApi ? new CantonScanApiClient(scanApi, network) : undefined;
  }

  getDefs() {
    return AllDefs[this.network];
  }

  async getCurrentOffset() {
    return (await this.api.performRequest(DefaultService.getV2StateLedgerEnd, "getCurrentOffset"))
      .offset;
  }

  async getTotalConsumedTraffic() {
    const status = await this.scanApiClient?.getTrafficStatus();

    return status?.traffic_status.actual.total_consumed;
  }

  async getRemainingTraffic() {
    const status = await this.scanApiClient?.getTrafficStatus();
    const actual = status?.traffic_status.actual;

    if (!RedstoneCommon.isDefined(actual)) {
      return undefined;
    }

    return actual.total_limit - actual.total_consumed;
  }

  async getConnectedSynchronizers() {
    const response = await this.api.performRequest(
      () => DefaultService.getV2StateConnectedSynchronizers(),
      "getConnectedSynchronizers"
    );

    return response.connectedSynchronizers ?? [];
  }

  async getSynchronizerId() {
    const synchronizers = await this.getConnectedSynchronizers();

    if (synchronizers.length !== 1) {
      const available = synchronizers
        .map(({ synchronizerAlias, synchronizerId }) => `${synchronizerAlias}: ${synchronizerId}`)
        .join(", ");
      throw new Error(
        `Expected exactly 1 connected synchronizer, found ${synchronizers.length}: ${available}`
      );
    }

    return synchronizers[0].synchronizerId;
  }

  async generateExternalPartyTopology(request: GenerateExternalPartyTopologyRequest) {
    return await this.api.performRequest(
      () => DefaultService.postV2PartiesExternalGenerateTopology(request),
      "generateExternalPartyTopology"
    );
  }

  async allocateExternalParty(request: AllocateExternalPartyRequest) {
    return await this.api.performRequest(
      () => DefaultService.postV2PartiesExternalAllocate(request),
      "allocateExternalParty"
    );
  }

  async getAmuletBalance(partyId: string) {
    const summary = await this.scanApiClient?.getAmuletHoldingsSummary(partyId);

    return summary?.total_available_coin ?? "0";
  }

  async getActiveContractsData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    limit = MAX_RESPONSE_LIMIT
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const filterDesc = Object.entries(filtersByParty)
      .map(
        ([partyId, filters]) =>
          `${partyId}:${filters.cumulative?.map((filter) => RedstoneCommon.stringify(filter.identifierFilter)).join(",")}`
      )
      .join(",");

    const collectingKey = `postV2StateActiveContracts {offset: ${offset}, limit: ${limit}, filter: [${filterDesc}]}`;
    const contracts = await this.api.performRequestCollected(
      () =>
        DefaultService.postV2StateActiveContracts(
          {
            filter: { filtersByParty },
            activeAtOffset: offset,
            verbose: false,
          },
          limit
        ),
      collectingKey
    );

    return contracts
      .filter(isJsActiveContract)
      .filter(
        (contract) =>
          !filter ||
          filter(
            contract.contractEntry.JsActiveContract.createdEvent.createArgument,
            contract.contractEntry.JsActiveContract.createdEvent.signatories
          )
      );
  }

  async getActiveContractData<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number
  ) {
    const adapters = await this.getActiveContractsData(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    const [adapter, ...rest] = adapters;
    if (rest.length > 0) {
      throw new Error(`Unable to determine contract data of ${adapters.length} contracts`);
    }

    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return makeActiveContractData<T>(createdEvent, synchronizerId);
  }

  async getMostActiveContractData<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    sorter?: CreatedArgumentCallback
  ) {
    let adapters = await this.getActiveContractsData(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    if (sorter) {
      adapters = _.sortBy(adapters, (contract) =>
        sorter(
          contract.contractEntry.JsActiveContract.createdEvent.createArgument,
          contract.contractEntry.JsActiveContract.createdEvent.signatories
        )
      );
    }

    const [adapter] = adapters;
    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return makeActiveContractData<T>(createdEvent, synchronizerId);
  }

  async getCreateContractEvents(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    deltaOffset = DEFAULT_DELTA_OFFSET,
    excludeArchived = false
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const contracts = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, offset - deltaOffset),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_ACS_DELTA
    );

    return extractCreatedEvents(contracts, filter, excludeArchived);
  }

  async getTransactionsForInterface(
    actAs: string,
    interfaceId: string,
    from: number,
    to: number,
    method: string
  ) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const result = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, from),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
      to
    );

    const updates = [];

    for (const { update } of result) {
      if (!("Transaction" in update)) {
        continue;
      }

      const updateId = update.Transaction.value.updateId;
      const fullUpdate = await this.api.performRequest(
        () =>
          DefaultService.postV2UpdatesUpdateById({
            updateId,
            updateFormat: {
              includeTransactions: {
                transactionShape:
                  TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
                eventFormat: {
                  filtersByParty: { [actAs]: {} },
                  verbose: false,
                },
              },
            },
          }),
        `getUpdates[updateId=${updateId}]`
      );

      const allEvents =
        "update" in fullUpdate && "Transaction" in fullUpdate.update
          ? (fullUpdate.update.Transaction.value.events ?? [])
          : [];

      const extracted = extractUpdateMetadata(allEvents, update.Transaction, method);

      updates.push(...extracted);
    }

    return updates;
  }

  async exerciseChoice<Arg extends object, Res = object>(
    actAs: string,
    command: { templateId: string; contractId: string; choice: string; choiceArgument: Arg },
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const { results, metadata } = await this.exerciseChoices<Arg, Res>(
      actAs,
      [command],
      timestamp,
      disclosedContracts
    );
    const [result] = Object.values(results);

    if (!result) {
      throw new Error(`No result for choice ${command.choice} on contract ${command.contractId}`);
    }

    return { result, metadata };
  }

  async exerciseChoicesWithoutWaiting<Arg extends object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");
    const commandId = CantonClient.getCommandId(choices, commands, timestamp);

    await this.api.performRequest(
      () =>
        DefaultService.postV2CommandsAsyncSubmit({
          commands: commands.map((command) => ({ ExerciseCommand: command })),
          commandId,
          actAs: [actAs],
          disclosedContracts,
          userId: !this.api.tokenProvider ? LOCAL_USER : undefined,
        }),
      `postV2CommandsAsyncSubmit ${CantonClient.describeCommandBatch(commands)}`
    );

    return commandId;
  }

  async exerciseChoices<Arg extends object, Res = object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");
    const commandId = CantonClient.getCommandId(choices, commands, timestamp);

    const result = await this.api.performRequest(
      () => {
        return DefaultService.postV2CommandsSubmitAndWaitForTransaction({
          commands: {
            commands: commands.map((command) => ({ ExerciseCommand: command })),
            commandId,
            actAs: [actAs],
            disclosedContracts,
            userId: !this.api.tokenProvider ? LOCAL_USER : undefined,
          },
          transactionFormat: {
            transactionShape: TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
            eventFormat: {
              filtersByParty: { [actAs]: {} },
              verbose: false,
            },
          },
        });
      },
      `postV2CommandsSubmitAndWaitForTransaction ${CantonClient.describeCommandBatch(commands)}`
    );

    const { events, synchronizerId, paidTrafficCost } = result.transaction;
    if (!RedstoneCommon.isDefined(events)) {
      throw new Error(`field events undefined even though explicitly requested`);
    }
    const results = extractExercisedResultsFromEvents<Res>(events, synchronizerId);

    return { results, metadata: { paidTrafficCost } as TransactionMetadata };
  }

  private async resolveFilterAndOffset(actAs: string, interfaceId: string, atOffset?: number) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const offset = atOffset ?? (await this.getCurrentOffset());

    return { filtersByParty, offset };
  }

  private async fetchUpdates(
    filtersByParty: Record<string, object>,
    beginExclusive: number,
    transactionShape: TransactionFormat.transactionShape,
    endInclusive?: number
  ) {
    return await this.api.performRequest(
      () =>
        DefaultService.postV2Updates({
          beginExclusive,
          endInclusive,
          verbose: false,
          updateFormat: {
            includeTransactions: {
              eventFormat: { filtersByParty, verbose: false },
              transactionShape,
            },
          },
        }),
      `postV2Updates ${RedstoneCommon.stringify(filtersByParty)}`
    );
  }

  private static getCommandId(choices: string, commands: unknown[], timestamp: Date) {
    return `batch-${choices}-${commands.length}-${timestamp.getTime()}-${Math.random().toFixed(4).substring(2)}`;
  }

  private static describeCommandBatch<Arg>(
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[]
  ) {
    const commandDesc = commands
      .map(({ contractId, choice }) => `${contractId}:${choice}`)
      .join(", ");

    return `batch[${commands.length}] (${commandDesc})`;
  }
}

export class JsonCantonApi extends CantonApi {
  private runningPromises: { [p: string]: Promise<unknown> | undefined } = {};

  async performRequestCollected<T>(
    promise: () => Promise<JsCantonError | T>,
    collectingKey: string
  ): Promise<T> {
    if (this.runningPromises[collectingKey]) {
      return (await this.runningPromises[collectingKey]) as T;
    }

    try {
      this.runningPromises[collectingKey] = this.performRequest(promise, collectingKey);

      return (await this.runningPromises[collectingKey]) as T;
    } finally {
      delete this.runningPromises[collectingKey];
    }
  }

  async performRequest<T>(promise: () => Promise<T | JsCantonError>, fnName = "performRequest") {
    OpenAPI.BASE = this.baseUrl;
    OpenAPI.TOKEN = this.tokenProvider;

    const name = `${fnName} with ${this.baseUrl}`;
    this.logger.info(`Calling ${name}`);

    return await unwrapResponse(this.logPerf(promise, name));
  }
}
