port: 4222

authorization {
  users = [
    { nkey: "UDHG5SLKGZTN6LNBQSFE6NOH6S7OQRYHFXZ4QBKJKY53XIEEVJ76KECU" }
  ]
}

allow_non_tls: true

tls {
  cert_file:       "/certs/server.crt"
  key_file:        "/certs/server.key"
  ca_file:         "/certs/ca.crt"
  verify:          true
  handshake_first: auto
}
