[package]
name = "common"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { version = "^1.3.0" }
redstone = { git = "https://github.com/redstone-finance/rust-sdk", tag = "2.0.0", default-features = false, features = ["radix"] }

[features]
default = []
mock-time = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.scripts]
publish = "resim publish ."
