/**
 * Measures the end-to-end price-publication latency for a Canton adapter, using the
 * ledger as the single source of truth:
 *
 *   T0  packageTimestamp  - node iteration timestamp
 *   T2  updateStartTimeMs - relayer's start of the update (payload's unsigned metadata)
 *   T3  writeTimestamp    - relayer's clock when the command was built (per attempt, so a
 *                           wrong-contract retry pushes it far past T2)
 *   T4  recordTime        - the commit on Canton
 *
 * There are two ways to read them, because event visibility differs per party:
 *
 *   - the updater party sees the `WritePrices` ExercisedEvent, which carries the payload
 *     (T0), its unsigned metadata (T2) and `currentTime` (T3); together with the
 *     `recordTime` (T4) of the enclosing transaction that gives all four timestamps;
 *   - the viewer party only sees CreatedEvents, but the adapter contract created by the
 *     consuming choice already holds `feedData` with per-feed `packageTimestamp` (T0) and
 *     `writeTimestamp` (T3) - everything except T2.
 *
 * Both paths are used; T2 is reported only for the updates where it is available.
 *
 * Usage:
 *   yarn measure-canton-latency          # endpoint + auth come from .env / RPC_URLS
 *
 * Env:
 *   TARGET_UPDATES  how many updates to collect (default 200)
 *   OFFSET_WINDOW   offset chunk size per request (default 3000; shrinks on node limits)
 *   PARTY_ID        reading party (defaults to the viewer party from canton-defs.json)
 *   INTERACTIVE     true to prompt for an MFA code
 *   OUT_CSV         path to also write one row per update
 */
import { RedstonePayload } from "@redstone-finance/protocol";
import { loggerFactory, RedstoneCommon } from "@redstone-finance/utils";
import "dotenv/config";
import _ from "lodash";
import { execSync } from "node:child_process";
import fs from "node:fs";
import { z } from "zod";
import {
  API_TYPE_JSON,
  CantonApi,
  JsonCantonApi,
  KeycloakTokenProvider,
  KeycloakTokenProviderOptions,
  makeKeycloakParams,
} from "../src";
import {
  DefaultService,
  Event,
  JsGetUpdatesResponse,
  TransactionFormat,
} from "../src/_autogenerated";
import { WRITE_PRICES_CHOICE } from "../src/adapters/PricesCantonContractAdapter";
import { IADAPTER_TEMPLATE_NAME } from "../src/adapters/PricesCantonReadOnlyAdapter";
import * as AllDefs from "../src/canton-defs.json";
import { CantonFeedId, decodeCantonFeedId } from "../src/utils/conversions";
import { packageTimestampOf, PriceData } from "../src/utils/price-feed-utils";
import { combineIntoId, makeInterfaceFilterByParty } from "../src/utils/utils";
import { readNetwork, readRpcUrls } from "./utils";

/** The participant caps a list response at `http-list-max-elements-limit`, 200 on mainnet. */
const PAGE_LIMIT = 200;
const MIN_OFFSET_WINDOW = 200;
const MAX_REQUESTS = 400;

const logger = loggerFactory("measure-canton-latency");

type WrittenFeed = {
  feedId: string;
  packageTimestampMs: number;
  writeTimestampMs: number;
};

type Sample = {
  updateId: string;
  offset: number;
  /** T4 */
  recordTimeMs: number;
  /** T3 */
  buildTimeMs: number;
  /** T0 */
  packageTimestampMs: number;
  /** T2, only readable from the payload, i.e. only via the ExercisedEvent */
  updateStartMs?: number;
  source: "exercised" | "created";
  dataPackageCount?: number;
  version?: string;
  componentName?: string;
  paidTrafficCost?: number;
  writtenFeeds: WrittenFeed[];
};

/**
 * Resolves the JSON Ledger API the same way CantonClientBuilder does: by `type` out of
 * RPC_URLS, not from API. The ledger API is served under a path on the Catalyst gateway,
 * so the bare participant host in API would 404.
 */
function readJsonApiSetup() {
  const jsonApis = RedstoneCommon.splitUrls(readRpcUrls(), (urlString) =>
    CantonApi.parseUrl(urlString)
  )[API_TYPE_JSON];

  if (!jsonApis?.length) {
    throw new Error(`No ${API_TYPE_JSON} URL found in RPC_URLS`);
  }

  return jsonApis[0];
}

function promptTotpSync(username: string): string {
  process.stderr.write(`\n[MFA] Enter TOTP code for ${username}: `);

  return execSync("read -r code && echo $code", { stdio: ["inherit", "pipe", "inherit"] })
    .toString()
    .trim();
}

function makeInteractiveKeycloakOptions(): KeycloakTokenProviderOptions {
  const params = makeKeycloakParams();

  return { ...params, getTotp: () => Promise.resolve(promptTotpSync(params.username)) };
}

/**
 * A raw JSON Ledger API handle: this script needs endpoints and response fields
 * CantonClient does not expose (e.g. millisecond-precision recordTime).
 *
 * Auth comes from CANTON_AUTH (the base64 blob the relayer gets as CANTON_<n>_AUTH) when
 * set, otherwise from the KEYCLOAK_* env vars.
 */
function makeScriptJsonApi(interactive = false) {
  const { baseUrl, clientId } = readJsonApiSetup();
  const auth = RedstoneCommon.getFromEnv("CANTON_AUTH", z.string().optional());
  const options = auth
    ? makeKeycloakParams(auth)
    : interactive
      ? makeInteractiveKeycloakOptions()
      : makeKeycloakParams();
  const tokenProvider = KeycloakTokenProvider.getInstance(
    clientId ? { ...options, clientId } : options
  );

  // parseUrl returns `origin + pathname`, so a host without a path yields a trailing
  // slash, which the generated client would concatenate into `//v2/...` and 404.
  return new JsonCantonApi(baseUrl.replace(/\/+$/, ""), () => tokenProvider.getToken());
}

function readTargetUpdates() {
  return RedstoneCommon.getFromEnv("TARGET_UPDATES", z.number().default(200));
}

function readOffsetWindow() {
  return RedstoneCommon.getFromEnv("OFFSET_WINDOW", z.number().default(3000));
}

function readOutCsvPath() {
  return RedstoneCommon.getFromEnv("OUT_CSV", z.string().optional());
}

/** canton-defs.json stores the signatory as `Party::<suffix>`; reuse that suffix. */
function defaultPartyId(signatory: string) {
  const suffix = signatory.split("::")[1];

  if (!suffix) {
    throw new Error(`Cannot derive a party suffix from signatory "${signatory}", set PARTY_ID`);
  }

  return `RedStoneOracleViewer::${suffix}`;
}

function readPartyId(signatory: string) {
  return RedstoneCommon.getFromEnv("PARTY_ID", z.string().default(defaultPartyId(signatory)));
}

function isTooManyElements(error: unknown) {
  return RedstoneCommon.stringifyError(error).includes("MAXIMUM_LIST_ELEMENTS");
}

/**
 * The consuming `WritePrices` choice creates a fresh adapter contract in the same
 * transaction, whose `feedData` already holds the newly written pills.
 */
function extractWrittenFeeds(events: Event[]): WrittenFeed[] {
  for (const event of events) {
    if (!("CreatedEvent" in event)) {
      continue;
    }

    const createArgument = event.CreatedEvent.createArgument as
      | { feedData?: [CantonFeedId, { priceData: PriceData }[]][] }
      | undefined;

    if (!createArgument?.feedData) {
      continue;
    }

    return createArgument.feedData
      .map(([feedId, records]) => {
        const newest = _.maxBy(records, (record) => Number(record.priceData.writeTimestamp));

        return newest
          ? {
              feedId: decodeCantonFeedId(feedId),
              packageTimestampMs: Number(packageTimestampOf(newest.priceData) ?? "0"),
              writeTimestampMs: Number(newest.priceData.writeTimestamp),
            }
          : undefined;
      })
      .filter(RedstoneCommon.isDefined);
  }

  return [];
}

function parsePayload(payloadHex: string) {
  const bytes = Uint8Array.from(Buffer.from(payloadHex.replace(/^0x/i, ""), "hex"));
  const { signedDataPackages, unsignedMetadata } = RedstonePayload.parse(bytes);

  const packageTimestamps = signedDataPackages.map(
    (signedDataPackage) => signedDataPackage.dataPackage.timestampMilliseconds
  );

  // `<metadataTimestamp>#<version>#<componentName>`, see ContractParamsProvider.getUnsignedMetadata
  const [timestampPart, version, componentName] = Buffer.from(unsignedMetadata)
    .toString("utf8")
    .split("#");

  return {
    packageTimestampMs: Math.max(...packageTimestamps),
    dataPackageCount: signedDataPackages.length,
    updateStartMs: Number(timestampPart),
    version,
    componentName,
  };
}

/** Full sample, requires the ExercisedEvent (updater party). */
function fromExercisedEvent(
  events: Event[],
  updateId: string,
  recordTimeMs: number,
  paidTrafficCost: number | undefined,
  writtenFeeds: WrittenFeed[]
): Sample | undefined {
  for (const event of events) {
    if (!("ExercisedEvent" in event) || event.ExercisedEvent.choice !== WRITE_PRICES_CHOICE) {
      continue;
    }

    const choiceArgument = event.ExercisedEvent.choiceArgument as {
      payloadHex?: string;
      currentTime?: string;
    };

    if (!choiceArgument.payloadHex || !choiceArgument.currentTime) {
      continue;
    }

    return {
      updateId,
      offset: event.ExercisedEvent.offset,
      recordTimeMs,
      buildTimeMs: Date.parse(choiceArgument.currentTime),
      source: "exercised",
      paidTrafficCost,
      writtenFeeds,
      ...parsePayload(choiceArgument.payloadHex),
    };
  }

  return undefined;
}

/**
 * Fallback for a party that only sees CreatedEvents: the pills written by this very
 * transaction are the ones stamped with the transaction's own build time, i.e. the newest
 * `writeTimestamp` in the created adapter contract.
 */
function fromCreatedEvents(
  updateId: string,
  offset: number,
  recordTimeMs: number,
  paidTrafficCost: number | undefined,
  writtenFeeds: WrittenFeed[]
): Sample | undefined {
  const buildTimeMs = _.max(writtenFeeds.map((feed) => feed.writeTimestampMs));

  if (!buildTimeMs) {
    return undefined;
  }

  const justWritten = writtenFeeds.filter((feed) => feed.writeTimestampMs === buildTimeMs);
  const packageTimestampMs = _.max(justWritten.map((feed) => feed.packageTimestampMs));

  if (!packageTimestampMs) {
    return undefined;
  }

  return {
    updateId,
    offset,
    recordTimeMs,
    buildTimeMs,
    packageTimestampMs,
    source: "created",
    paidTrafficCost,
    writtenFeeds,
  };
}

function extractSample(response: JsGetUpdatesResponse): Sample | undefined {
  if (!response.update || !("Transaction" in response.update)) {
    return undefined;
  }

  const transaction = response.update.Transaction.value;
  const events = transaction.events;
  const recordTimeMs = Date.parse(transaction.recordTime);
  const writtenFeeds = extractWrittenFeeds(events);

  return (
    fromExercisedEvent(
      events,
      transaction.updateId,
      recordTimeMs,
      transaction.paidTrafficCost,
      writtenFeeds
    ) ??
    fromCreatedEvents(
      transaction.updateId,
      transaction.offset,
      recordTimeMs,
      transaction.paidTrafficCost,
      writtenFeeds
    )
  );
}

type Api = ReturnType<typeof makeScriptJsonApi>;

async function fetchUpdates(
  api: Api,
  partyId: string,
  interfaceId: string,
  beginExclusive: number,
  endInclusive: number
) {
  return await api.performRequest(
    () =>
      DefaultService.postV2Updates(
        {
          beginExclusive,
          endInclusive,
          verbose: false,
          updateFormat: {
            includeTransactions: {
              eventFormat: {
                filtersByParty: makeInterfaceFilterByParty(interfaceId, partyId),
                verbose: false,
              },
              transactionShape: TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
            },
          },
        },
        PAGE_LIMIT
      ),
    `postV2Updates[${beginExclusive}..${endInclusive}]`
  );
}

/**
 * Offsets are opaque counters, so "the last N updates" cannot be turned into a range up
 * front. Walk backwards from the ledger end in chunks, accumulating as we go, and shrink
 * the chunk (permanently - the density does not change) whenever the node refuses the
 * result set as too large.
 */
async function collectSamples(
  api: Api,
  partyId: string,
  interfaceId: string,
  ledgerEnd: number,
  targetUpdates: number
) {
  const samples: Sample[] = [];
  let chunk = readOffsetWindow();
  let cursor = ledgerEnd;
  let requests = 0;

  while (samples.length < targetUpdates && cursor > 0 && requests < MAX_REQUESTS) {
    const beginExclusive = Math.max(0, cursor - chunk);
    requests++;

    let responses;
    try {
      responses = await fetchUpdates(api, partyId, interfaceId, beginExclusive, cursor);
    } catch (error) {
      if (!isTooManyElements(error) || chunk <= MIN_OFFSET_WINDOW) {
        throw error;
      }
      chunk = Math.max(MIN_OFFSET_WINDOW, Math.floor(chunk / 2));
      logger.info(`Node list limit hit, chunk=${chunk}`);
      continue;
    }

    const found = responses.map(extractSample).filter(RedstoneCommon.isDefined);
    samples.push(...found);
    logger.info(
      `offsets ${beginExclusive}..${cursor} → ${found.length} update${RedstoneCommon.getS(found.length)} (${samples.length}/${targetUpdates})`
    );

    cursor = beginExclusive;
  }

  return _(samples).sortBy("offset").sortedUniqBy("offset").takeRight(targetUpdates).value();
}

function sortAscending(values: number[]) {
  return values.filter((value) => Number.isFinite(value)).toSorted((a, b) => a - b);
}

function percentile(sortedValues: number[], p: number) {
  if (!sortedValues.length) {
    return NaN;
  }

  const index = Math.min(sortedValues.length - 1, Math.floor((p / 100) * sortedValues.length));

  return sortedValues[index];
}

function describe(segment: string, values: number[]) {
  const sorted = sortAscending(values);

  return {
    segment,
    n: sorted.length,
    min: Math.round(sorted[0] ?? NaN),
    p50: Math.round(percentile(sorted, 50)),
    p95: Math.round(percentile(sorted, 95)),
    p99: Math.round(percentile(sorted, 99)),
    max: Math.round(percentile(sorted, 100)),
  };
}

function reportSegments(samples: Sample[]) {
  const withPayload = samples.filter((sample) => RedstoneCommon.isDefined(sample.updateStartMs));

  const rows = [
    describe(
      "T0→T3  node package → command built",
      samples.map((s) => s.buildTimeMs - s.packageTimestampMs)
    ),
    describe(
      "T3→T4  submit → commit (recordTime)",
      samples.map((s) => s.recordTimeMs - s.buildTimeMs)
    ),
    describe(
      "T0→T4  END TO END",
      samples.map((s) => s.recordTimeMs - s.packageTimestampMs)
    ),
    describe(
      "T0→T2  node package → update start",
      withPayload.map((s) => s.updateStartMs! - s.packageTimestampMs)
    ),
    describe(
      // Not just serialization: exerciseChoice runs inside withContractDataCaching, which
      // refetches the adapter contract id and retries on a wrong-contract error, so this
      // segment absorbs those retries too.
      "T2→T3  payload build + contract-id refresh",
      withPayload.map((s) => s.buildTimeMs - s.updateStartMs!)
    ),
  ];

  logger.info("Latency per segment [ms]");
  console.table(rows);
}

function reportPerFeed(samples: Sample[]) {
  const rows = _(samples)
    .flatMap((sample) =>
      sample.writtenFeeds
        // a feed not touched by this transaction carries an older writeTimestamp
        .filter((feed) => feed.writeTimestampMs === sample.buildTimeMs)
        .map((feed) => ({
          feedId: feed.feedId,
          e2eMs: sample.recordTimeMs - feed.packageTimestampMs,
        }))
    )
    .groupBy("feedId")
    .map((entries, feedId) => {
      const sorted = sortAscending(entries.map((entry) => entry.e2eMs));

      return {
        feedId,
        writes: sorted.length,
        e2e_p50: Math.round(percentile(sorted, 50)),
        e2e_p95: Math.round(percentile(sorted, 95)),
        e2e_max: Math.round(percentile(sorted, 100)),
      };
    })
    .sortBy("feedId")
    .value();

  if (!rows.length) {
    logger.warn("No feed was written in the collected updates");

    return;
  }

  logger.info("End-to-end per written feed [ms]");
  console.table(rows);
}

function reportContext(samples: Sample[]) {
  const first = samples[0];
  const last = _.last(samples)!;
  const gaps = _.zip(samples.slice(0, -1), samples.slice(1)).map(
    ([previous, next]) => next!.recordTimeMs - previous!.recordTimeMs
  );
  const sortedGaps = _.sortBy(gaps);
  const bySource = _.countBy(samples, "source") as Partial<Record<Sample["source"], number>>;

  logger.info(
    `Collected ${samples.length} updates (${bySource.exercised ?? 0} via ExercisedEvent, ` +
      `${bySource.created ?? 0} via CreatedEvent), offsets ${first.offset}..${last.offset}`
  );
  logger.info(
    `Window: ${new Date(first.recordTimeMs).toISOString()} .. ${new Date(last.recordTimeMs).toISOString()}`
  );
  logger.info(
    `Interval between commits [ms]: p50=${Math.round(percentile(sortedGaps, 50))} ` +
      `p95=${Math.round(percentile(sortedGaps, 95))} max=${Math.round(_.last(sortedGaps) ?? NaN)}`
  );

  if (RedstoneCommon.isDefined(last.dataPackageCount)) {
    logger.info(
      `Payload: ${last.dataPackageCount} data packages, component=${last.componentName}, version=${last.version}`
    );
  }
}

function writeCsv(path: string, samples: Sample[]) {
  const header = [
    "updateId",
    "offset",
    "source",
    "packageTimestampMs",
    "updateStartMs",
    "buildTimeMs",
    "recordTimeMs",
    "nodeToBuildMs",
    "submitToCommitMs",
    "endToEndMs",
    "paidTrafficCost",
    "writtenFeeds",
  ].join(",");

  const rows = samples.map((sample) =>
    [
      sample.updateId,
      sample.offset,
      sample.source,
      sample.packageTimestampMs,
      sample.updateStartMs ?? "",
      sample.buildTimeMs,
      sample.recordTimeMs,
      sample.buildTimeMs - sample.packageTimestampMs,
      sample.recordTimeMs - sample.buildTimeMs,
      sample.recordTimeMs - sample.packageTimestampMs,
      sample.paidTrafficCost ?? "",
      sample.writtenFeeds
        .filter((feed) => feed.writeTimestampMs === sample.buildTimeMs)
        .map((feed) => feed.feedId)
        .join("|"),
    ].join(",")
  );

  fs.writeFileSync(path, [header, ...rows].join("\n") + "\n");
  logger.info(`Wrote ${rows.length} rows to ${path}`);
}

async function main() {
  const network = readNetwork();
  const defs = AllDefs[network];
  const interfaceId = combineIntoId(defs.interfaceId, IADAPTER_TEMPLATE_NAME);
  const partyId = readPartyId(defs.signatory);
  const api = makeScriptJsonApi(
    RedstoneCommon.getFromEnv("INTERACTIVE", z.boolean().default(false))
  );

  logger.info(`network=${network} interfaceId=${interfaceId} partyId=${partyId}`);

  const { offset: ledgerEnd } = await api.performRequest(
    DefaultService.getV2StateLedgerEnd,
    "getCurrentOffset"
  );

  const samples = await collectSamples(
    api,
    partyId,
    interfaceId,
    ledgerEnd ?? 0,
    readTargetUpdates()
  );

  if (!samples.length) {
    throw new Error(
      `No updates found. Check PARTY_ID/interfaceId, or raise OFFSET_WINDOW/MAX_REQUESTS.`
    );
  }

  reportContext(samples);
  reportSegments(samples);
  reportPerFeed(samples);

  const outCsv = readOutCsvPath();
  if (outCsv) {
    writeCsv(outCsv, samples);
  }
}

void main();
