/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace RedstoneMulticall3 {
  export type RedstoneCall3Struct = {
    target: PromiseOrValue<string>;
    allowFailure: PromiseOrValue<boolean>;
    callData: PromiseOrValue<BytesLike>;
    gasLimit: PromiseOrValue<BigNumberish>;
  };

  export type RedstoneCall3StructOutput = [
    string,
    boolean,
    string,
    BigNumber
  ] & {
    target: string;
    allowFailure: boolean;
    callData: string;
    gasLimit: BigNumber;
  };

  export type ResultStruct = {
    success: PromiseOrValue<boolean>;
    returnData: PromiseOrValue<BytesLike>;
  };

  export type ResultStructOutput = [boolean, string] & {
    success: boolean;
    returnData: string;
  };
}

export interface RedstoneMulticall3Interface extends utils.Interface {
  functions: {
    "aggregate3((address,bool,bytes,uint256)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "aggregate3"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "aggregate3",
    values: [RedstoneMulticall3.RedstoneCall3Struct[]]
  ): string;

  decodeFunctionResult(functionFragment: "aggregate3", data: BytesLike): Result;

  events: {};
}

export interface RedstoneMulticall3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RedstoneMulticall3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aggregate3(
      calls: RedstoneMulticall3.RedstoneCall3Struct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  aggregate3(
    calls: RedstoneMulticall3.RedstoneCall3Struct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    aggregate3(
      calls: RedstoneMulticall3.RedstoneCall3Struct[],
      overrides?: CallOverrides
    ): Promise<RedstoneMulticall3.ResultStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    aggregate3(
      calls: RedstoneMulticall3.RedstoneCall3Struct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aggregate3(
      calls: RedstoneMulticall3.RedstoneCall3Struct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
