[package]
name = "multi_feed_price_adapter"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { version = "^1.3.0" }
common = { path = "../../common" }

[dev-dependencies]
scrypto-test = { version = "^1.3.0" }
redstone_testing = { git = "https://github.com/redstone-finance/rust-sdk", tag = "2.0.0" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.scripts]
publish = "resim publish ."
