[package]
name = "multi_feed_price_adapter"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
scrypto = { version = "^1.3.0" }
common = { path = "../../common", default-features = false, optional = true }

[dev-dependencies]
scrypto-test = { version = "^1.3.0" }
common = { path = "../../common", features = ["test_helpers"] }

[features]
real_network = ["common/real_network"]
real_network_test = ["common/real_network_test"]
default = ["common/default"]
test_sim_env = ["common/test_sim_env"]

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.scripts]
publish = "resim publish ."
