[workspace]
resolver = "2"
members = [
  "contracts/*",
]

[workspace.dependencies]
hex = "0.4.3"
hex-literal = { version = "1.0.0" }
redstone = { git = "https://github.com/redstone-finance/rust-sdk", tag = "2.1.0-pre2", default-features = false }
redstone_testing = { git = "https://github.com/redstone-finance/rust-sdk", tag = "redstone-testing-v0.2.1", default-features = false }
soroban-sdk = "22.0.8"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
