condense_wildcard_suffixes = true
edition = "2024"
format_code_in_doc_comments = true
match_block_trailing_comma = true
reorder_impl_items = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
