[workspace]

members = [
    "rust-sdk",
    "redstone_casper",
    "contracts/price_adapter",
    "contracts/price_relay_adapter",
    "contracts/price_feed",
    "contracts/tests",
]

[profile.release]
codegen-units = 1
lto = true
