[package]
name = "common"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
scrypto = { version = "^1.3.0" }
redstone = { path = "../rust-sdk", default-features = false, optional = true }

[dev-dependencies]
scrypto-test = { version = "^1.3.0" }

[features]
real_network = ["redstone/crypto_radix", "redstone/network_radix"]
real_network_test = ["redstone/crypto_radix", "redstone/network_radix"]
default = ["redstone/crypto_radix", "redstone/network_radix", "redstone/helpers", "redstone/print_debug"]
test_sim_env = ["redstone/print_debug"]
test_helpers = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.scripts]
publish = "resim publish ."
