[project]
authors = ["Łukasz Kalbarczyk"]
entry = "prices.sw"
forc-version = "0.63.1"
license = "Apache-2.0"
name = "prices"
organization = "RedStone"

[dependencies]
redstone = { path = "../redstone-fuel-sdk" }
