import { RedstoneCommon } from "@redstone-finance/utils";
import type { ApiRequestOptions } from "./_autogenerated/core/ApiRequestOptions";
import { CantonNetwork } from "./CantonNetwork";
import * as AllDefs from "./contracts.json";

type TrafficStatusResponse = {
  traffic_status: {
    actual: {
      total_consumed: number;
      total_limit: number;
    };
    target: {
      total_purchased: number;
    };
  };
};

const HEADERS = { "Content-Type": "application/json" };
const MAX_RETRIES = 3;

export class CantonScanApiClient {
  Defs: (typeof AllDefs)["devnet"];

  constructor(
    private readonly httpProxyUrl: string,
    readonly network: CantonNetwork = "devnet",
    private readonly tokenProvider?: (options: ApiRequestOptions) => Promise<string>
  ) {
    this.Defs = AllDefs[network];
  }

  async getRemainingTraffic() {
    const nodeDefs = this.Defs.node;

    const result = await this.postWithProxy<TrafficStatusResponse>(
      `${nodeDefs.scanApiUrl}/domains/${nodeDefs.globalDomain}/members/PAR::${nodeDefs.participantPartyId}/traffic-status`
    );
    const actual = result.data.traffic_status.actual;

    return actual.total_limit - actual.total_consumed;
  }

  private async postWithProxy<T>(url: string, method = "GET") {
    const token = await this.tokenProvider?.({ method: "GET", url: "" });
    const authHeader = token ? { Authorization: `Bearer ${token}` } : undefined;

    return await RedstoneCommon.axiosPostWithRetries<T>(
      this.httpProxyUrl,
      {
        method,
        url,
      },
      {
        maxRetries: MAX_RETRIES,
        headers: { ...HEADERS, ...authHeader },
      }
    );
  }
}
