import { loggerFactory, RedstoneCommon } from "@redstone-finance/utils";
import _ from "lodash";
import {
  DefaultService,
  DisclosedContract,
  JsCantonError,
  OpenAPI,
  TransactionFormat,
} from "./_autogenerated";
import type { ApiRequestOptions } from "./_autogenerated/core/ApiRequestOptions";
import { CantonNetwork } from "./CantonNetwork";
import { CantonScanApiClient } from "./CantonScanApiClient";
import * as AllDefs from "./contracts.json";
import { ContractFilter, CreatedArgumentCallback, extractPriceEvents } from "./price-feed-utils";
import {
  isCreatedEvent,
  isJsActiveContract,
  isTransactionUpdate,
  makeActiveContractData,
  makeInterfaceFilterByParty,
  unwrapResponse,
} from "./utils";

const DEFAULT_DELTA_OFFSET = 1000;
const LOCAL_USER = "redstone-canton-connector";
const MAX_RESPONSE_LIMIT = 200;
const SENDER_SEPARATOR = "/";

export class CantonClient {
  private readonly logger = loggerFactory("canton-client");

  Defs: (typeof AllDefs)["devnet"];
  scanApiClient: CantonScanApiClient;

  constructor(
    private readonly baseUrl: string,
    network: CantonNetwork = "devnet",
    private readonly tokenProvider?: (options: ApiRequestOptions) => Promise<string>
  ) {
    this.Defs = AllDefs[network];

    this.scanApiClient = new CantonScanApiClient(
      baseUrl.split("/participants")[0] + "/http-proxy",
      network,
      tokenProvider
    );
  }

  async getCurrentOffset() {
    return (await this.performRequest(DefaultService.getV2StateLedgerEnd, "getCurrentOffset"))
      .offset;
  }

  async getRemainingTraffic() {
    return await this.scanApiClient.getRemainingTraffic();
  }

  private async fetchActiveContracts(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    limit = MAX_RESPONSE_LIMIT
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const contracts = await this.performRequest(
      () =>
        DefaultService.postV2StateActiveContracts(
          {
            filter: { filtersByParty },
            activeAtOffset: offset,
            verbose: false,
          },
          limit
        ),
      `postV2StateActiveContracts ${RedstoneCommon.stringify(filtersByParty)}`
    );

    return contracts
      .filter(isJsActiveContract)
      .filter(
        (contract) =>
          !filter ||
          filter(
            contract.contractEntry.JsActiveContract.createdEvent.createArgument,
            contract.contractEntry.JsActiveContract.createdEvent.signatories
          )
      );
  }

  async getActiveContractsData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    limit = MAX_RESPONSE_LIMIT
  ) {
    return await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset, limit);
  }

  async getActiveContractWithPayload<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number
  ) {
    const adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    const [adapter, ...rest] = adapters;
    if (rest.length > 0) {
      throw new Error(`Unable to determine contract data of ${adapters.length} contracts`);
    }

    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return {
      ...makeActiveContractData(createdEvent, synchronizerId),
      createArgument: createdEvent.createArgument as T,
    };
  }

  async getActiveContractData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number
  ) {
    const adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    const [adapter, ...rest] = adapters;
    if (rest.length > 0) {
      throw new Error(`Unable to determine contract data of ${adapters.length} contracts`);
    }

    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return makeActiveContractData(createdEvent, synchronizerId);
  }

  async getMostActiveContractWithPayload<T = unknown>(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    sorter?: CreatedArgumentCallback
  ) {
    let adapters = await this.fetchActiveContracts(actAs, interfaceId, filter, atOffset);
    if (adapters.length === 0) {
      throw new Error("No active contract data");
    }

    if (sorter) {
      adapters = _.sortBy(adapters, (contract) =>
        sorter(
          contract.contractEntry.JsActiveContract.createdEvent.createArgument,
          contract.contractEntry.JsActiveContract.createdEvent.signatories
        )
      );
    }

    const [adapter] = adapters;
    const { createdEvent, synchronizerId } = adapter.contractEntry.JsActiveContract;

    return {
      ...makeActiveContractData(createdEvent, synchronizerId),
      createArgument: createdEvent.createArgument as T,
    };
  }

  async getMostActiveContractData(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    sorter?: CreatedArgumentCallback
  ) {
    const { createArgument: _, ...contractData } = await this.getMostActiveContractWithPayload(
      actAs,
      interfaceId,
      filter,
      atOffset,
      sorter
    );

    return contractData;
  }

  async getCreateContractEvents(
    actAs: string,
    interfaceId: string,
    filter?: ContractFilter,
    atOffset?: number,
    deltaOffset = DEFAULT_DELTA_OFFSET,
    excludeArchived = false
  ) {
    const { filtersByParty, offset } = await this.resolveFilterAndOffset(
      actAs,
      interfaceId,
      atOffset
    );
    const contracts = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, offset - deltaOffset),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_ACS_DELTA
    );

    const transactions = contracts
      .map((contract) =>
        isTransactionUpdate(contract.update) ? contract.update.Transaction : undefined
      )
      .filter(RedstoneCommon.isDefined);

    const archivedContractIds = excludeArchived
      ? new Set(
          transactions
            .flatMap((transaction) => transaction.value.events ?? [])
            .filter((event) => "ArchivedEvent" in event)
            .map((event) => event.ArchivedEvent.contractId)
        )
      : new Set();

    const createdEvents = transactions
      .map((transaction) => transaction.value.events?.filter((event) => isCreatedEvent(event)))
      .filter((list) => list?.length)
      .filter(RedstoneCommon.isDefined);

    return createdEvents
      .flat()
      .filter(
        (createdEvent) =>
          !filter ||
          filter(createdEvent.CreatedEvent.createArgument, createdEvent.CreatedEvent.signatories)
      )
      .map((createdEvent) => createdEvent.CreatedEvent)
      .filter((createdEvent) => !archivedContractIds.has(createdEvent.contractId));
  }

  async getTransactionsForInterface(
    actAs: string,
    interfaceId: string,
    from: number,
    to: number,
    method: string
  ) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const result = await this.fetchUpdates(
      filtersByParty,
      Math.max(0, from),
      TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
      to
    );

    const updates = [];

    for (const { update } of result) {
      if (!("Transaction" in update)) {
        continue;
      }

      const updateId = update.Transaction.value.updateId;
      const fullUpdate = await this.performRequest(
        () =>
          DefaultService.postV2UpdatesUpdateById({
            updateId,
            updateFormat: {
              includeTransactions: {
                transactionShape:
                  TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
                eventFormat: {
                  filtersByParty: { [actAs]: {} },
                  verbose: false,
                },
              },
            },
          }),
        `getUpdates[updateId=${updateId}]`
      );

      const allEvents =
        "update" in fullUpdate && "Transaction" in fullUpdate.update
          ? (fullUpdate.update.Transaction.value.events ?? [])
          : [];

      const priceEvents = extractPriceEvents(allEvents);

      const events = update.Transaction.value.events ?? [];

      const createdEvent = events.find((e) => "CreatedEvent" in e)?.CreatedEvent;
      const adapterId =
        (createdEvent?.createArgument as { adapterId: string } | undefined)?.adapterId ?? "";

      for (const event of events) {
        if (!("ExercisedEvent" in event) || event.ExercisedEvent.choice !== method) {
          continue;
        }

        if (!("payloadHex" in event.ExercisedEvent.choiceArgument)) {
          continue;
        }

        const choice = event.ExercisedEvent.choiceArgument as { payloadHex: string };

        const arg = choice.payloadHex;
        const block = event.ExercisedEvent.offset;
        const timeSecs = RedstoneCommon.msToSecs(Date.parse(update.Transaction.value.recordTime));
        const to = adapterId;
        const from = event.ExercisedEvent.actingParties?.join(SENDER_SEPARATOR) ?? "";

        const updateId = update.Transaction.value.updateId;
        const cost = update.Transaction.value.paidTrafficCost;

        updates.push({ arg, block, timeSecs, from, to, updateId, priceEvents, cost });
      }
    }

    return updates;
  }

  async exerciseChoice<Arg extends object, Res = object>(
    actAs: string,
    command: { templateId: string; contractId: string; choice: string; choiceArgument: Arg },
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ): Promise<Res> {
    const results = await this.exerciseChoices<Arg, Res>(
      actAs,
      [command],
      timestamp,
      disclosedContracts
    );
    const [result] = Object.values(results);

    if (!result) {
      throw new Error(`No result for choice ${command.choice} on contract ${command.contractId}`);
    }

    return result;
  }

  async exerciseChoicesWithoutWaiting<Arg extends object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");
    const commandId = `batch-${choices}-${timestamp.getTime()}`;

    await this.performRequest(
      () =>
        DefaultService.postV2CommandsAsyncSubmit({
          commands: commands.map((command) => ({ ExerciseCommand: command })),
          commandId,
          actAs: [actAs],
          disclosedContracts,
          userId: !this.tokenProvider ? LOCAL_USER : undefined,
        }),
      `postV2CommandsAsyncSubmit batch[${commands.length}]`
    );

    return commandId;
  }

  async exerciseChoices<Arg extends object, Res = object>(
    actAs: string,
    commands: { templateId: string; contractId: string; choice: string; choiceArgument: Arg }[],
    timestamp: Date,
    disclosedContracts?: DisclosedContract[]
  ) {
    const choices = [...new Set(commands.map((c) => c.choice))].join(",");

    const result = await this.performRequest(
      () =>
        DefaultService.postV2CommandsSubmitAndWaitForTransaction({
          commands: {
            commands: commands.map((command) => ({ ExerciseCommand: command })),
            commandId: `batch-${choices}-${commands.length}-${timestamp.getTime()}`,
            actAs: [actAs],
            disclosedContracts,
            userId: !this.tokenProvider ? LOCAL_USER : undefined,
          },
          transactionFormat: {
            transactionShape: TransactionFormat.transactionShape.TRANSACTION_SHAPE_LEDGER_EFFECTS,
            eventFormat: {
              filtersByParty: { [actAs]: {} },
              verbose: false,
            },
          },
        }),
      `postV2CommandsSubmitAndWaitForTransaction batch[${commands.length}]`
    );

    if (result.transaction.paidTrafficCost) {
      this.logger.info("tx cost", { paidTraffix: result.transaction.paidTrafficCost });
    }

    const { events, synchronizerId } = result.transaction;
    if (!RedstoneCommon.isDefined(events)) {
      throw new Error(`field events undefined even though explicitly requested`);
    }
    const results: Record<string, Res> = {};

    for (const event of events) {
      if (!("ExercisedEvent" in event)) {
        continue;
      }

      const exercisedEvent = event.ExercisedEvent;

      if (exercisedEvent.consuming) {
        const createdEvent = events.find(
          (e) =>
            "CreatedEvent" in e &&
            e.CreatedEvent.nodeId > exercisedEvent.nodeId &&
            e.CreatedEvent.nodeId <= exercisedEvent.lastDescendantNodeId
        );

        if (createdEvent && "CreatedEvent" in createdEvent) {
          const newContractId = createdEvent.CreatedEvent.contractId;
          results[newContractId] = makeActiveContractData(
            createdEvent.CreatedEvent,
            synchronizerId
          ) as unknown as Res;
          continue;
        }

        continue;
      }

      const resultStr =
        typeof exercisedEvent.exerciseResult === "string"
          ? exercisedEvent.exerciseResult
          : undefined;

      if (resultStr) {
        const matchingCreate = events.find(
          (e) => "CreatedEvent" in e && e.CreatedEvent.contractId === resultStr
        );
        if (matchingCreate && "CreatedEvent" in matchingCreate) {
          results[exercisedEvent.contractId] = makeActiveContractData(
            matchingCreate.CreatedEvent,
            synchronizerId
          ) as unknown as Res;
          continue;
        }
      }

      results[exercisedEvent.contractId] = exercisedEvent.exerciseResult as Res;
    }

    return results;
  }

  private async resolveFilterAndOffset(actAs: string, interfaceId: string, atOffset?: number) {
    const filtersByParty = makeInterfaceFilterByParty(interfaceId, actAs);
    const offset = atOffset ?? (await this.getCurrentOffset());

    return { filtersByParty, offset };
  }

  private async fetchUpdates(
    filtersByParty: Record<string, object>,
    beginExclusive: number,
    transactionShape: TransactionFormat.transactionShape,
    endInclusive?: number
  ) {
    return await this.performRequest(
      () =>
        DefaultService.postV2Updates({
          beginExclusive,
          endInclusive,
          verbose: false,
          updateFormat: {
            includeTransactions: {
              eventFormat: { filtersByParty, verbose: false },
              transactionShape,
            },
          },
        }),
      `postV2Updates ${RedstoneCommon.stringify(filtersByParty)}`
    );
  }

  private async performRequest<T>(
    promise: () => Promise<T | JsCantonError>,
    fnName = "performRequest"
  ) {
    OpenAPI.BASE = this.baseUrl;
    OpenAPI.TOKEN = this.tokenProvider;

    this.logger.info(`Calling ${fnName}`);

    return await unwrapResponse(promise());
  }
}
