import { RedstoneCommon } from "@redstone-finance/utils";
import { Event, JsGetUpdatesResponse, Transaction } from "./_autogenerated";
import { ContractFilter, extractPriceEvents } from "./price-feed-utils";
import { isCreatedEvent, isTransactionUpdate, makeActiveContractData } from "./utils";

const SENDER_SEPARATOR = "/";

export function extractExercisedResultsFromEvents<Res>(events: Event[], synchronizerId: string) {
  const results: Record<string, Res> = {};

  for (const event of events) {
    if (!("ExercisedEvent" in event)) {
      continue;
    }

    const exercisedEvent = event.ExercisedEvent;

    if (exercisedEvent.consuming) {
      const createdEvent = events.find(
        (e) =>
          "CreatedEvent" in e &&
          e.CreatedEvent.nodeId > exercisedEvent.nodeId &&
          e.CreatedEvent.nodeId <= exercisedEvent.lastDescendantNodeId
      );

      if (createdEvent && "CreatedEvent" in createdEvent) {
        const newContractId = createdEvent.CreatedEvent.contractId;
        results[newContractId] = makeActiveContractData(
          createdEvent.CreatedEvent,
          synchronizerId
        ) as unknown as Res;
        continue;
      }

      continue;
    }

    const resultStr =
      typeof exercisedEvent.exerciseResult === "string" ? exercisedEvent.exerciseResult : undefined;

    if (resultStr) {
      const matchingCreate = events.find(
        (e) => "CreatedEvent" in e && e.CreatedEvent.contractId === resultStr
      );
      if (matchingCreate && "CreatedEvent" in matchingCreate) {
        results[exercisedEvent.contractId] = makeActiveContractData(
          matchingCreate.CreatedEvent,
          synchronizerId
        ) as unknown as Res;
        continue;
      }
    }

    results[exercisedEvent.contractId] = exercisedEvent.exerciseResult as Res;
  }

  return results;
}

export function extractCreatedEvents(
  contracts: JsGetUpdatesResponse[],
  filter: ContractFilter | undefined,
  excludeArchived: boolean
) {
  const transactions = contracts
    .map((contract) =>
      isTransactionUpdate(contract.update) ? contract.update.Transaction : undefined
    )
    .filter(RedstoneCommon.isDefined);

  const archivedContractIds = excludeArchived
    ? new Set(
        transactions
          .flatMap((transaction) => transaction.value.events ?? [])
          .filter((event) => "ArchivedEvent" in event)
          .map((event) => event.ArchivedEvent.contractId)
      )
    : new Set();

  const createdEvents = transactions
    .map((transaction) => transaction.value.events?.filter((event) => isCreatedEvent(event)))
    .filter((list) => list?.length)
    .filter(RedstoneCommon.isDefined);

  return createdEvents
    .flat()
    .filter(
      (createdEvent) =>
        !filter ||
        filter(createdEvent.CreatedEvent.createArgument, createdEvent.CreatedEvent.signatories)
    )
    .map((createdEvent) => createdEvent.CreatedEvent)
    .filter((createdEvent) => !archivedContractIds.has(createdEvent.contractId));
}

export function extractUpdateMetadata(
  allEvents: Event[],
  transaction: Transaction,
  method: string
) {
  const priceEvents = extractPriceEvents(allEvents);
  const events = transaction.value.events ?? [];

  const createdEvent = events.find((e) => "CreatedEvent" in e)?.CreatedEvent;
  const adapterId =
    (createdEvent?.createArgument as { adapterId: string } | undefined)?.adapterId ?? "";

  const updates = [];

  for (const event of events) {
    if (!("ExercisedEvent" in event) || event.ExercisedEvent.choice !== method) {
      continue;
    }

    if (!("payloadHex" in event.ExercisedEvent.choiceArgument)) {
      continue;
    }

    const choice = event.ExercisedEvent.choiceArgument as { payloadHex: string };

    const arg = choice.payloadHex;
    const block = event.ExercisedEvent.offset;
    const timeSecs = RedstoneCommon.msToSecs(Date.parse(transaction.value.recordTime));
    const to = adapterId;
    const from = event.ExercisedEvent.actingParties?.join(SENDER_SEPARATOR) ?? "";

    const updateId = transaction.value.updateId;
    const cost = transaction.value.paidTrafficCost;

    updates.push({ arg, block, timeSecs, from, to, updateId, priceEvents, cost });
  }

  return updates;
}
