import { LastRoundDetails } from "@redstone-finance/sdk";
import _ from "lodash";
import { CreatedEvent, Event } from "./_autogenerated";
import { convertDecimalValue, decodeFeedId, getArrayifiedFeedId } from "./conversions";

export const IPRICE_PILL_TEMPLATE_NAME = `IRedStonePricePill:IRedStonePricePill`;
export const PRICE_PILL_TEMPLATE_NAME = `RedStonePricePill:RedStonePricePill`;
export const PRICE_UPDATE_EVENT_TEMPLATE_NAME = `PriceUpdateEvent:PriceUpdateEvent`;
export const READ_DATA_CHOICE = "ReadData";
export const READ_FEED_ID_CHOICE = "ReadFeedId";
export const READ_DESCRIPTION_CHOICE = "ReadDescription";
export const ARCHIVE_CHOICE = "Archive";

export type CreatedArgumentCallback<R = unknown> = (
  createArgument: unknown,
  signatories?: string[]
) => R;
export type ContractFilter = CreatedArgumentCallback<boolean>;

export type PriceData = {
  value: string;
  timestamp: string;
  writeTimestamp: string;
};

export function parsePriceData(result: PriceData): LastRoundDetails {
  return {
    lastDataPackageTimestampMS: Number.parseInt(result.timestamp),
    lastBlockTimestampMS: Number.parseInt(result.writeTimestamp),
    lastValue: convertDecimalValue(result.value),
  };
}

export function findNewestContract(events: CreatedEvent[]): CreatedEvent | undefined {
  if (!events.length) {
    return undefined;
  }

  return _.maxBy(events, (e) =>
    Number((e.createArgument as { priceData?: PriceData } | undefined)?.priceData?.timestamp ?? 0)
  );
}

export function createFeedIdFilter(
  arrayifiedFeedIds: number[][],
  adapterId?: string
): ContractFilter {
  return ((createArgument: { feedId: string[]; adapterId: string }) =>
    (!adapterId || createArgument.adapterId === adapterId) &&
    arrayifiedFeedIds.some((arrayified) =>
      _.isEqual(createArgument.feedId.map(Number), arrayified)
    )) as ContractFilter;
}

export function createStalenessFilter(keepFresh: boolean = true): ContractFilter {
  return ((createArgument: { priceData: { writeTimestamp: string }; stalenessMs: string }) => {
    const currentTime = Date.now();
    const writeTimestamp = Number(createArgument.priceData.writeTimestamp);
    const stalenessMs = Number(createArgument.stalenessMs);
    const isFresh = currentTime - writeTimestamp <= stalenessMs;

    return keepFresh === isFresh;
  }) as ContractFilter;
}

export function groupEventsByFeedId(
  events: CreatedEvent[],
  feedIds: string[],
  arrayifiedFeedIds: Map<string, number[]>
): Record<string, CreatedEvent[]> {
  return _.groupBy(events, (event) =>
    feedIds.find((feedId) =>
      _.isEqual(
        (event.createArgument as { feedId: string[] } | undefined)?.feedId.map(Number),
        arrayifiedFeedIds.get(feedId)
      )
    )
  );
}

export function buildArrayifiedFeedIds(feedIds: string[]): Map<string, number[]> {
  return new Map(feedIds.map((feedId) => [feedId, getArrayifiedFeedId(feedId)]));
}

type PriceEvent = {
  name: string;
  feedId: string;
  args: unknown[];
} & ({ updated: true; value: number } | { updated: false });

function extractPricePillEvent(createArgument: unknown): PriceEvent {
  const { feedId, priceData } = createArgument as {
    feedId: string[];
    priceData: { value: string; timestamp: string; writeTimestamp: string };
  };

  const feedIdStr = decodeFeedId(feedId);

  return {
    name: "ValueUpdate",
    feedId: feedIdStr,
    args: [priceData.value, feedIdStr, priceData.writeTimestamp],
    updated: true,
    value: Number(priceData.value),
  };
}

function extractPriceUpdateEvent(createArgument: unknown): PriceEvent | undefined {
  const { feedId, isSkipped, error } = createArgument as {
    feedId: string[];
    isSkipped: boolean;
    error?: string;
  };

  if (!isSkipped || error === undefined) {
    return undefined;
  }

  const feedIdStr = decodeFeedId(feedId);
  const name = classifySkipReason(error);

  return {
    name,
    feedId: feedIdStr,
    args: [feedIdStr],
    updated: false,
  };
}

function classifySkipReason(error: string): string {
  if (error.includes("Wrong timestamps")) {
    return "UpdateSkipDueToDataTimestamp";
  }

  if (error.includes("Signer count not achieved")) {
    return "UpdateSkipDueToInvalidValue";
  }

  return "UpdateSkipDueToBlockTimestamp";
}

export function extractPriceEvents(events: Event[]) {
  const result: Record<string, PriceEvent> = {};

  for (const event of events) {
    if (!("CreatedEvent" in event)) {
      continue;
    }

    const created = event.CreatedEvent;

    if (created.templateId.includes(PRICE_PILL_TEMPLATE_NAME)) {
      const priceEvent = extractPricePillEvent(created.createArgument);
      result[priceEvent.feedId] = priceEvent;
      continue;
    }

    if (created.templateId.includes(PRICE_UPDATE_EVENT_TEMPLATE_NAME)) {
      const priceEvent = extractPriceUpdateEvent(created.createArgument);
      if (priceEvent) {
        result[priceEvent.feedId] = priceEvent;
      }
    }
  }

  return result;
}
