import { RedstoneCommon } from "@redstone-finance/utils";
import z from "zod";
import {
  CreatedEvent,
  Event,
  JsCantonError,
  JsContractEntry,
  Map_Filters,
  Transaction,
  Update,
} from "./_autogenerated";

export type DamlTuple2<T = string, U = string> = { _1: T; _2: U };

const CONTRACT_NOT_FOUND_ERROR = "CONTRACT_NOT_FOUND";

export function isApiError(e: unknown): e is Error & { body: { code: string; cause: string } } {
  const error = e as Error & { body: { code: string; cause: string } };

  return (
    "body" in error &&
    RedstoneCommon.isDefined(error.body) &&
    typeof error.body === "object" &&
    "code" in error.body &&
    "cause" in error.body
  );
}

export function isContractNotFoundError(
  e: unknown
): e is Error & { message: typeof CONTRACT_NOT_FOUND_ERROR } {
  if (e instanceof AggregateError) {
    return e.errors.some(isContractNotFoundError);
  }

  const error = e as Error;

  return "message" in error && error.message === CONTRACT_NOT_FOUND_ERROR;
}

export async function unwrapResponse<T>(promise: Promise<T | JsCantonError>) {
  try {
    const response = await promise;

    if (typeof response === "object" && response !== null && "cause" in response) {
      throw new Error(response.cause);
    }

    return response;
  } catch (error) {
    if (isApiError(error)) {
      throw new Error(error.body.code, { cause: error.body.cause });
    }

    throw error;
  }
}

export function makeInterfaceFilterByParty(interfaceId: string, partyId: string) {
  const partyFilter = {
    cumulative: [
      {
        identifierFilter: {
          InterfaceFilter: {
            value: {
              interfaceId,
              includeInterfaceView: true,
              includeCreatedEventBlob: true,
            },
          },
        },
      },
    ],
  };

  const filtersByParty: Map_Filters = {};
  filtersByParty[partyId] = partyFilter;

  return filtersByParty;
}

export function isJsActiveContractEntry(contractEntry: JsContractEntry) {
  return "JsActiveContract" in contractEntry;
}

export function isTransactionUpdate(update: Update): update is { Transaction: Transaction } {
  return "Transaction" in update;
}

export function isCreatedEvent(event: Event) {
  return "CreatedEvent" in event;
}

export interface ActiveContractData {
  contractId: string;
  synchronizerId?: string;
  createdEventBlob?: string;
}

export function makeActiveContractData(
  createdEvent: CreatedEvent,
  synchronizerId: string = ""
): ActiveContractData {
  return {
    contractId: createdEvent.contractId,
    synchronizerId,
    createdEventBlob: RedstoneCommon.useDefaultIfEmpty(createdEvent.createdEventBlob, undefined),
  };
}

export function readPartyIds() {
  return {
    viewerPartyId: RedstoneCommon.getFromEnv("VIEWER_PARTY_ID"),
    updaterPartyId: RedstoneCommon.getFromEnv("UPDATER_PARTY_ID", z.string().optional()),
  };
}

export function readPartySuffix() {
  return RedstoneCommon.getFromEnv("PARTY_SUFFIX");
}
