import { JsCantonError, Map_Filters } from "./_autogenerated";

export type Daml2Tuple<T = string, U = string> = { _1: T; _2: U };

export async function unwrapResponse<T>(promise: Promise<T | JsCantonError>) {
  const response = await promise;

  if (typeof response === "object" && response !== null && "code" in response) {
    throw new Error(response.cause);
  }

  return response;
}

export function makeInterfaceFilterByParty(interfaceId: string, partyId: string) {
  const partyFilter = {
    cumulative: [
      {
        identifierFilter: {
          InterfaceFilter: {
            value: {
              interfaceId,
              includeInterfaceView: true,
              includeCreatedEventBlob: false,
            },
          },
        },
      },
    ],
  };

  const filtersByParty: Map_Filters = {};
  filtersByParty[partyId] = partyFilter;

  return filtersByParty;
}
