import { execSync } from "child_process";
import "dotenv/config";
import path from "node:path";
import { setTimeout } from "timers/promises";
import { createKeypairFile } from "./create-keypair-file";
import { getAccountInfo } from "./get-account-info";
import { PRICE_ADAPTER_NAME, readCluster } from "./utils";

export const RDS_PROGRAM_ADDRESS =
  "rds8J7VKqLQgzDr7vS59dkQga3B1BotgFy8F7LSLC74";

async function deploy() {
  const cluster = readCluster();
  const pkData = createKeypairFile();
  const walletFilePath = path.join("..", pkData.filePath);

  await getAccountInfo(pkData.publicKey, cluster);
  const anchorArgs = `--program-name ${PRICE_ADAPTER_NAME.replace("_", "-")} --provider.cluster ${cluster} --provider.wallet ${walletFilePath}`;
  const deployCmd = `cd solana && anchor build ${anchorArgs} --idl-ts ${__dirname}/../src/_autogenerated --idl ${__dirname}/../src/_autogenerated && anchor deploy ${anchorArgs} --program-keypair ${RDS_PROGRAM_ADDRESS}.json`;

  execSync(deployCmd, { stdio: ["inherit", "inherit", "inherit"] });
}

async function main() {
  await deploy();

  await setTimeout(15_000); // wait 15 seconds before continuing
}

void main();
