[package]
name = "price-adapter"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "price_adapter"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
dev = []

[dependencies]
anchor-lang = { version = "0.30.1",  features = ["init-if-needed"] }
redstone = { git = "https://github.com/redstone-finance/rust-sdk", branch = "main", default-features = false, features=["solana"] }

[dev-dependencies]
rand = { version = "0.8.4", features = ["std"] }
