[package]
edition = "2021"
name = "price-adapter"
version = "0.1.3"


[dependencies]
alloy-primitives = { version = "=0.8.20", default-features = false }
alloy-sol-types = { version = "=0.8.20", default-features = false }
openzeppelin-stylus = "=0.2.0"
redstone = { git = "https://github.com/redstone-finance/rust-sdk", tag = "2.1.0-pre", default-features = false }
stylus-sdk = "=0.9.0"

[dev-dependencies]
stylus-sdk = { version = "0.9.0", features = ["stylus-test"] }
[lib]
crate-type = ["cdylib", "lib"]

[features]
e2e = []
export-abi = ["openzeppelin-stylus/export-abi"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = false
opt-level = "s"
overflow-checks = false
panic = "abort"
rpath = false
strip = true

[[bin]]
name = "price-adapter"
path = "src/main.rs"
