services:
  operator-attester:
    image: public.ecr.aws/z6z4q0a5/prod-avs-othentic-client:b52e8208
    platform: linux/arm64
    command: [
        "node",
        "attester",
        "/ip4/3.251.232.65/tcp/3000/p2p/12D3KooWSBMPURmCU5B8nuXkUw1Tq26FuvDg5LsEcs4WX8dqAxWJ",
        "--avs-webapi",
        "http://operator-validation-api",
        "--avs-webapi-port",
        "4002",
        "--p2p.port",
        "3000",
        "--l1-chain",
        "mainnet",
        "--l2-chain",
        "base",
        "--p2p.datadir",
        ".othentic/data/p2p",
        # "--announced-addresses",
        # "${ANNOUNCED_ADDRESSES}",
      ]
    env_file:
      - .env
    volumes:
      - .othentic:/app/.othentic
    ports:
      - "3000:3000"
  operator-validation-api:
    image: public.ecr.aws/z6z4q0a5/prod-avs-validation-api:b52e8208
    platform: linux/arm64
