/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mulitcall3Sol from "./Mulitcall3.sol";
export * as redstoneMulitcall3Sol from "./RedstoneMulitcall3.sol";
