import { type BN, BorshAccountsCoder, type Idl } from "@coral-xyz/anchor";
import { convertIdlToCamelCase } from "@coral-xyz/anchor/dist/cjs/idl.js";
import idl from "../_autogenerated/redstone_solana_price_adapter.json";

const PRICE_DATA_ACCOUNT_NAME = "priceData";

const priceDataCoder = new BorshAccountsCoder(convertIdlToCamelCase(idl as unknown as Idl));

export interface PriceData {
  feedId: number[];
  value: number[];
  timestamp: BN;
  writeTimestamp: BN | null;
  writeSlotNumber: BN;
  decimals: number;
}

export function decodePriceData(data: Buffer): PriceData {
  return priceDataCoder.decode(PRICE_DATA_ACCOUNT_NAME, data);
}
