/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.0
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

export type { PricesAbi } from './PricesAbi';

export { PricesAbi__factory } from './factories/PricesAbi__factory';
