/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.42.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { PricesAbi } from './PricesAbi';

export { PricesAbi__factory } from './factories/PricesAbi__factory';
