/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.0
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Vec } from "./common";

interface PricesAbiInterface extends Interface {
  functions: {
    get_prices: FunctionFragment;
    init: FunctionFragment;
    read_prices: FunctionFragment;
    read_timestamp: FunctionFragment;
    write_prices: FunctionFragment;
  };
}

export class PricesAbi extends Contract {
  interface: PricesAbiInterface;
  functions: {
    get_prices: InvokeFunction<[feed_ids: Vec<BigNumberish>, payload: Bytes], Vec<BN>>;
    init: InvokeFunction<[signers: Vec<string>, signer_count_threshold: BigNumberish], void>;
    read_prices: InvokeFunction<[feed_ids: Vec<BigNumberish>], Vec<BN>>;
    read_timestamp: InvokeFunction<[], BN>;
    write_prices: InvokeFunction<[feed_ids: Vec<BigNumberish>, payload: Bytes], Vec<BN>>;
  };
}
