import { U256Input, U256Output } from "./autogenerated/PricesAbi";
import assert from "assert";

export function u256(value: string): U256Input {
  return { a: 0, b: 0, c: 0, d: value };
}

export function num(value: U256Output): number {
  assert(
    value.c.toNumber() + value.b.toNumber() + value.a.toNumber() == 0,
    "The returned value must be number-convertible"
  );

  return value.d.toNumber();
}
