import { Prices } from "../autogenerated";
import { FuelContractConnector } from "../FuelContractConnector";
import { FuelPricesContractAdapter } from "./FuelPricesContractAdapter";

export type FuelPricesContract = Prices;

export class FuelPricesContractConnector extends FuelContractConnector<FuelPricesContractAdapter> {
  async getContract(): Promise<FuelPricesContract> {
    return await Promise.resolve(new Prices(this.contractId, this.wallet));
  }

  async getAdapter() {
    return await Promise.resolve(
      new FuelPricesContractAdapter(await this.getContract(), this.getGasLimit())
    );
  }
}
