[project]
authors = ["Łukasz Kalbarczyk"]
entry = "redstone_core.sw"
forc-version = "0.66.2"
license = "Apache-2.0"
name = "redstone_core"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
redstone = { git = "https://github.com/redstone-finance/redstone-fuel-sdk", tag = "v0.66.2" }

[proxy]
enabled = true
