[project]
authors = ["Łukasz Kalbarczyk"]
entry = "redstone_core.sw"
forc-version = "0.64.0"
license = "Apache-2.0"
name = "redstone_core"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
redstone = { git = "https://github.com/redstone-finance/redstone-fuel-sdk", tag = "testnet-0.64.0" }

[proxy]
address = "0x823f963f71032f016a0e6d8ee06fc63dad843f91f1f1de8336a48d3f4cdd0442"
enabled = true

