import { loggerFactory, RedstoneCommon } from "@redstone-finance/utils";
import { ApiError } from "../_autogenerated";
import { CantonClient, ContractFilter } from "../CantonClient";
import { ActiveContractData, isContractNotFoundError } from "../utils";

const RETRY_CONFIG: Omit<RedstoneCommon.RetryConfig, "fn"> = {
  maxRetries: 3,
  waitBetweenMs: 100,
  backOff: {
    backOffBase: 1.5,
  },
};

export abstract class CantonContractAdapter {
  protected readonly logger = loggerFactory("canton-contract-adapter");
  protected activeContractData?: ActiveContractData;

  protected constructor(
    protected readonly client: CantonClient,
    protected readonly interfaceId: string,
    protected readonly templateName: string
  ) {}

  async fetchContractData(offset?: number, client = this.client) {
    return await client.getActiveContractData(
      this.getInterfaceId(),
      this.getContractFilter(),
      offset
    );
  }

  protected getInterfaceId() {
    return `${this.interfaceId}:${this.templateName}`;
  }

  protected abstract getContractFilter(): ContractFilter;

  protected async exerciseChoice<Res, Arg extends object = object>(
    choice: string,
    argument: Arg,
    offset: number | undefined = undefined,
    addCurrentTime = false,
    client = this.client,
    disclosedContractData?: Required<ActiveContractData>[]
  ) {
    return await RedstoneCommon.retry({
      ...RETRY_CONFIG,
      fn: async () =>
        await this.performExerciseChoice<Arg, Res>(
          choice,
          argument,
          offset,
          addCurrentTime,
          client,
          disclosedContractData
        ),
    })();
  }

  private async performExerciseChoice<Arg extends object, Res>(
    choice: string,
    argument: Arg,
    offset: number | undefined = undefined,
    addCurrentTime = false,
    client = this.client,
    disclosedContractData?: Required<ActiveContractData>[]
  ) {
    this.activeContractData ??= await this.fetchContractData(offset, client);
    const timestamp = new Date();

    const choiceArgument = addCurrentTime
      ? { ...argument, currentTime: timestamp.toISOString() }
      : argument;

    try {
      const result: Res = await client.exerciseChoice(
        {
          choice,
          contractId: this.activeContractData.contractId,
          choiceArgument,
          templateId: this.getInterfaceId(),
        },
        timestamp,
        disclosedContractData
      );

      return result;
    } catch (error) {
      const apiError = error as ApiError;
      this.logger.error(
        `${RedstoneCommon.stringify((apiError.body as { cause: unknown }).cause)} ${RedstoneCommon.stringifyError(error)}`
      );

      if (isContractNotFoundError(error)) {
        this.activeContractData = undefined;
      }

      throw error;
    }
  }
}
