[project]
authors = ["Łukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.63.6"
license = "Apache-2.0"
name = "contract_invoker"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
