import { RedstoneCommon } from "@redstone-finance/utils";
import z from "zod";
import {
  CreatedEvent,
  Event,
  JsActiveContract,
  JsCantonError,
  JsContractEntry,
  JsGetActiveContractsResponse,
  Map_Filters,
  Transaction,
  Update,
} from "../_autogenerated";

const CONTRACT_NOT_FOUND_ERROR = "CONTRACT_NOT_FOUND" as const;
const LOCAL_VERDICT_INACTIVE_CONTRACTS_ERROR = "LOCAL_VERDICT_INACTIVE_CONTRACTS" as const;
const LOCAL_VERDICT_LOCKED_CONTRACTS = "LOCAL_VERDICT_LOCKED_CONTRACTS" as const;
const SEP = ":";
const PARTY_ID_REGEX = /^[^:]+::1220[0-9a-f]{64}$/i;

export function isApiError(e: unknown): e is Error & { body: { code: string; cause: string } } {
  const error = e as Error & { body: { code: string; cause: string } };

  return (
    "body" in error &&
    RedstoneCommon.isDefined(error.body) &&
    typeof error.body === "object" &&
    "code" in error.body &&
    "cause" in error.body
  );
}

export function isWrongContractError(e: unknown): e is Error & {
  message:
    | typeof CONTRACT_NOT_FOUND_ERROR
    | typeof LOCAL_VERDICT_INACTIVE_CONTRACTS_ERROR
    | typeof LOCAL_VERDICT_LOCKED_CONTRACTS;
} {
  if (e instanceof AggregateError) {
    return e.errors.some(isWrongContractError);
  }

  const error = e as Error;

  return (
    "message" in error &&
    (error.message === CONTRACT_NOT_FOUND_ERROR ||
      error.message === LOCAL_VERDICT_INACTIVE_CONTRACTS_ERROR ||
      error.message === LOCAL_VERDICT_LOCKED_CONTRACTS)
  );
}

export async function unwrapResponse<T>(promise: Promise<T | JsCantonError>) {
  try {
    const response = await promise;

    if (typeof response === "object" && response !== null && "cause" in response) {
      throw new Error(response.cause);
    }

    return response;
  } catch (error) {
    if (isApiError(error)) {
      // eslint-disable-next-line preserve-caught-error -- todo
      throw new Error(error.body.code, { cause: error.body.cause });
    }

    throw error;
  }
}

export function makeInterfaceFilterByParty(interfaceId: string, partyId: string) {
  const partyFilter = {
    cumulative: [
      {
        identifierFilter: {
          InterfaceFilter: {
            value: {
              interfaceId,
              includeInterfaceView: true,
              includeCreatedEventBlob: true,
            },
          },
        },
      },
    ],
  };

  const filtersByParty: Map_Filters = {};
  filtersByParty[partyId] = partyFilter;

  return filtersByParty;
}

export function isJsActiveContract(response: JsGetActiveContractsResponse): response is {
  workflowId: string;
  contractEntry: { JsActiveContract: JsActiveContract };
} {
  return isJsActiveContractEntry(response.contractEntry);
}

function isJsActiveContractEntry(contractEntry: JsContractEntry) {
  return "JsActiveContract" in contractEntry;
}

export function isTransactionUpdate(update: Update): update is { Transaction: Transaction } {
  return "Transaction" in update;
}

export function isCreatedEvent(event: Event) {
  return "CreatedEvent" in event;
}

export type DisclosedContractData = Required<Omit<ActiveContractData, "createArgument">>;

export interface ActiveContractData<T = unknown> {
  contractId: string;
  createArgument?: T;
  synchronizerId?: string;
  createdEventBlob?: string;
}

export function makeActiveContractData<T = unknown>(
  createdEvent: CreatedEvent,
  synchronizerId: string = ""
): ActiveContractData<T> & Required<Pick<ActiveContractData<T>, "createArgument">> {
  return {
    contractId: createdEvent.contractId,
    synchronizerId,
    createArgument: createdEvent.createArgument as T,
    createdEventBlob: RedstoneCommon.useDefaultIfEmpty(createdEvent.createdEventBlob, undefined),
  };
}

export function readCantonPartyIds() {
  return {
    viewerPartyId: RedstoneCommon.getFromEnv("CANTON_VIEWER_PARTY_ID"),
    updaterPartyId: RedstoneCommon.getFromEnv("CANTON_UPDATER_PARTY_ID", z.string().optional()),
  };
}

export function assertValidPartyId(partyId: string) {
  if (!PARTY_ID_REGEX.test(partyId)) {
    throw new Error(`Invalid Canton party id: ${partyId}`);
  }

  return partyId;
}

export function combineIntoId(interfaceId: string, templateName: string) {
  return `${interfaceId}${SEP}${templateName}`;
}

export function decodeJwtPayload<T>(token: string) {
  return JSON.parse(Buffer.from(token.split(".")[1], "base64url").toString()) as T;
}
