# https://raw.githubusercontent.com/radixdlt/official-examples/refs/heads/main/scrypto-design-patterns/blueprint-proxy/oracle-generic-proxy-with-global/src/lib.rs
[package]
name = "proxy"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { version = "1.3.0" }

[features]
default = []
test = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
