export const ACCOUNT_ID = 6;

// random keys for now
export const MULTISIG_SIGNERS = [
  "GBWMG4Z6PPL3IKCGWY7Q7AUFOYVSKDMU5JTUYX5IJKPJZMEPXNMBRYSO",
  "GBC3S4G7IIJITBEXSTQWKGPFQDTB5OQGMGPJMZNGQU6WQJ3UCV2A3DCE",
  "GBW7HCW4JESTOYFXPMPI6PACOSTEN7ZIUWPNCQQV6RKCWBGFFDSLZVPC",
];

export const MULTISIG_TRESHOLD = 2;
export const INITIAL_ACCOUNT_AMOUNT_XLM = 10;

export const MULTISIG_ADDRESS = "GDI3GOJTPXCOBQTBAIHIIWBLKKWPRFMBSBLIR5MXOFJFPBLWFNWWAWNK";
