export const ACCOUNT_ID = 6;

// random keys for now
export const MULTISIG_SIGNERS = [
  "GBC3S4G7IIJITBEXSTQWKGPFQDTB5OQGMGPJMZNGQU6WQJ3UCV2A3DCE",
  "GBJHGKGESIVPF27EDDQ3MQFRIJG3KFTEQ3UC7J62TGORBP57P4TARSFE",
];

export const MULTISIG_TRESHOLD = 1;
export const INITIAL_ACCOUNT_AMOUNT = 100;

export const MULTISIG_ADDRESS = "GDGIOJJL3A2MHPC4HPITJEMZJBTOOYB3H3RS34XCB2GFQQWS4BXEAUX3";
