[project]
authors = ["Łukasz Kalbarczyk"]
entry = "redstone_adapter.sw"
forc-version = "0.65.2"
license = "Apache-2.0"
name = "redstone_adapter"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
redstone = { git = "https://github.com/redstone-finance/redstone-fuel-sdk", branch = "sway-0.65.2" }

[proxy]
address = "0xd7ae6565970e67593caf50c5e0e0ada1a7ded444754334741058fe5dab2f7c7b"
enabled = true
