/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mulitcall3Sol from "./Mulitcall3.sol";
export type { mulitcall3Sol };
import type * as redstoneMulitcall3Sol from "./RedstoneMulitcall3.sol";
export type { redstoneMulitcall3Sol };
export * as factories from "./factories";
export type { Multicall3 } from "./Mulitcall3.sol/Multicall3";
export { Multicall3__factory } from "./factories/Mulitcall3.sol/Multicall3__factory";
export type { RedstoneMulticall3 } from "./RedstoneMulitcall3.sol/RedstoneMulticall3";
export { RedstoneMulticall3__factory } from "./factories/RedstoneMulitcall3.sol/RedstoneMulticall3__factory";
