import { ActiveContractData } from "../src";
import { Event, JsGetUpdatesResponse, Transaction } from "../src/_autogenerated";
import {
  extractCreatedEvents,
  extractExercisedResultsFromEvents,
  extractUpdateMetadata,
} from "../src/utils/extract-utils";
import { PRICE_PILL_TEMPLATE_NAME } from "../src/utils/price-feed-utils";
import {
  BASE_TS,
  BLOB,
  BTC_STR,
  CID,
  ETH_STR,
  getPackageTemplateName,
  makeArchivedEvent,
  makeCreatedEvent,
  makeExercisedEvent,
  PRICE_ADAPTER_ID,
  SIGNATORY,
} from "./test-helpers";

describe("extractExercisedResultsFromEvents", () => {
  it("maps a consuming exercise to the newly created descendant contract", () => {
    const created = makeCreatedEvent({
      nodeId: 11,
      contractId: CID.ethNewPill,
      createdEventBlob: BLOB.ethNewPill,
    });
    const exercised = makeExercisedEvent({
      consuming: true,
      nodeId: 10,
      lastDescendantNodeId: 20,
      contractId: CID.ethOldPill,
    });

    const results = extractExercisedResultsFromEvents<ActiveContractData>(
      [{ ExercisedEvent: exercised }, { CreatedEvent: created }],
      "sync-primary"
    );

    expect(results[CID.ethNewPill]).toEqual({
      contractId: CID.ethNewPill,
      synchronizerId: "sync-primary",
      createdEventBlob: BLOB.ethNewPill,
    });
  });

  it("resolves a non-consuming exercise with a contractId string result", () => {
    const created = makeCreatedEvent({
      contractId: CID.btcResolved,
      createdEventBlob: BLOB.btc,
    });
    const exercised = makeExercisedEvent({
      contractId: CID.btcChoice,
      exerciseResult: CID.btcResolved,
    });

    const results = extractExercisedResultsFromEvents<ActiveContractData>(
      [{ ExercisedEvent: exercised }, { CreatedEvent: created }],
      "sync-1"
    );

    expect(results[CID.btcChoice]).toEqual({
      contractId: CID.btcResolved,
      synchronizerId: "sync-1",
      createdEventBlob: BLOB.btc,
    });
  });

  it("records the raw exerciseResult when it is not a matchable contractId", () => {
    const exercised = makeExercisedEvent({
      contractId: CID.ccChoice,
      exerciseResult: { details: "ok" },
    });

    const results = extractExercisedResultsFromEvents<{ details: string }>(
      [{ ExercisedEvent: exercised }],
      "sync-1"
    );

    expect(results[CID.ccChoice]).toEqual({ details: "ok" });
  });
});

describe("extractCreatedEvents", () => {
  const wrap = (events: Event[]): JsGetUpdatesResponse => ({
    update: {
      Transaction: {
        value: {
          updateId: "u",
          commandId: "c",
          workflowId: "w",
          effectiveAt: "2026-04-22T00:00:00Z",
          events,
          offset: 1,
          synchronizerId: "sync-1",
          recordTime: "2026-04-22T00:00:00Z",
        },
      },
    } as never,
  });

  it("collects CreatedEvents across transactions", () => {
    const eth = makeCreatedEvent({ contractId: CID.eth });
    const btc = makeCreatedEvent({ contractId: CID.btc });

    const result = extractCreatedEvents(
      [wrap([{ CreatedEvent: eth }]), wrap([{ CreatedEvent: btc }])],
      undefined,
      false
    );

    expect(result.map((e) => e.contractId)).toEqual([CID.eth, CID.btc]);
  });

  it("applies the provided filter predicate", () => {
    const eth = makeCreatedEvent({
      contractId: CID.eth,
      createArgument: { feedId: ETH_STR },
    });
    const btc = makeCreatedEvent({
      contractId: CID.btc,
      createArgument: { feedId: BTC_STR },
    });

    const result = extractCreatedEvents(
      [wrap([{ CreatedEvent: eth }, { CreatedEvent: btc }])],
      (arg) => (arg as { feedId?: string[] }).feedId?.join(",") === ETH_STR.join(","),
      false
    );

    expect(result.map((e) => e.contractId)).toEqual([CID.eth]);
  });

  it("drops archived contracts when excludeArchived=true", () => {
    const eth = makeCreatedEvent({ contractId: CID.eth });
    const btc = makeCreatedEvent({ contractId: CID.btc });
    const archive: Event = {
      ArchivedEvent: makeArchivedEvent({ contractId: CID.btc }),
    };

    const result = extractCreatedEvents(
      [wrap([{ CreatedEvent: eth }, { CreatedEvent: btc }, archive])],
      undefined,
      true
    );

    expect(result.map((e) => e.contractId)).toEqual([CID.eth]);
  });

  it("keeps archived contracts when excludeArchived=false", () => {
    const btc = makeCreatedEvent({ contractId: CID.btc });
    const archive: Event = {
      ArchivedEvent: makeArchivedEvent({ contractId: CID.btc }),
    };

    const result = extractCreatedEvents([wrap([{ CreatedEvent: btc }, archive])], undefined, false);

    expect(result.map((e) => e.contractId)).toEqual([CID.btc]);
  });
});

describe("extractUpdateMetadata", () => {
  const makeTransaction = (events: Event[], paidTrafficCost?: number): Transaction =>
    ({
      value: {
        updateId: "update-ETH-BTC",
        commandId: "c",
        workflowId: "w",
        effectiveAt: "2026-04-22T00:00:00Z",
        events,
        offset: 42,
        synchronizerId: "sync-1",
        recordTime: "2026-04-22T00:00:00Z",
        paidTrafficCost,
      },
    }) as Transaction;

  it("collects one update per matching ExercisedEvent with the chosen method and payloadHex", () => {
    const adapterCreated: Event = {
      CreatedEvent: makeCreatedEvent({
        contractId: CID.adapter,
        createArgument: { adapterId: PRICE_ADAPTER_ID },
      }),
    };
    const pillCreated: Event = {
      CreatedEvent: makeCreatedEvent({
        templateId: getPackageTemplateName(PRICE_PILL_TEMPLATE_NAME),
        contractId: CID.ethPill,
        createArgument: {
          feedId: ETH_STR,
          priceData: {
            value: "25000",
            timestamp: String(BASE_TS),
            writeTimestamp: String(BASE_TS),
          },
        },
      }),
    };
    const exercised: Event = {
      ExercisedEvent: makeExercisedEvent({
        offset: 99,
        choice: "WritePrices",
        choiceArgument: { payloadHex: "0xdeadbeef" },
        actingParties: [SIGNATORY],
      }),
    };

    const transaction = makeTransaction([adapterCreated, pillCreated, exercised], 4_242);

    const updates = extractUpdateMetadata(
      [adapterCreated, pillCreated, exercised],
      transaction,
      "WritePrices"
    );

    expect(updates).toHaveLength(1);
    expect(updates[0]).toMatchObject({
      arg: "0xdeadbeef",
      block: 99,
      to: PRICE_ADAPTER_ID,
      from: SIGNATORY,
      updateId: "update-ETH-BTC",
      cost: 4_242,
    });
    expect(updates[0].priceEvents["ETH"]).toMatchObject({ name: "ValueUpdate", value: 25_000 });
  });

  it("skips ExercisedEvents whose choice does not match", () => {
    const exercised: Event = {
      ExercisedEvent: makeExercisedEvent({
        choice: "Archive",
        choiceArgument: { payloadHex: "0xcafe" },
      }),
    };
    const transaction = makeTransaction([exercised], 10);

    expect(extractUpdateMetadata([exercised], transaction, "WritePrices")).toEqual([]);
  });

  it("skips ExercisedEvents without a payloadHex in choiceArgument", () => {
    const exercised: Event = {
      ExercisedEvent: makeExercisedEvent({
        choice: "WritePrices",
        choiceArgument: { somethingElse: true },
      }),
    };
    const transaction = makeTransaction([exercised], 10);

    expect(extractUpdateMetadata([exercised], transaction, "WritePrices")).toEqual([]);
  });

  it("defaults adapterId ('to') to empty string when no CreatedEvent is present", () => {
    const exercised: Event = {
      ExercisedEvent: makeExercisedEvent({
        choice: "WritePrices",
        choiceArgument: { payloadHex: "0xabc" },
      }),
    };
    const transaction = makeTransaction([exercised]);

    const [update] = extractUpdateMetadata([exercised], transaction, "WritePrices");

    expect(update.to).toBe("");
    expect(update.cost).toBeUndefined();
  });
});
