import { Event } from "../src/_autogenerated";
import {
  buildArrayifiedFeedIds,
  createFeedIdFilter,
  createStalenessFilter,
  extractPriceEvents,
  findNewestContract,
  groupEventsByFeedId,
  parsePriceData,
  PRICE_PILL_TEMPLATE_NAME,
  PRICE_UPDATE_EVENT_TEMPLATE_NAME,
} from "../src/utils/price-feed-utils";
import {
  BASE_TS,
  BTC_ARR,
  BTC_STR,
  CC_ARR,
  CC_STR,
  CID,
  ETH_ARR,
  ETH_STR,
  getPackageTemplateName,
  makeArchivedEvent,
  makeCreatedEvent,
  PRICE_ADAPTER_ID,
} from "./test-helpers";

const pillEvent = (feedId: number[], value: string, timestamp: string): Event => ({
  CreatedEvent: makeCreatedEvent({
    templateId: getPackageTemplateName(PRICE_PILL_TEMPLATE_NAME),
    createArgument: {
      feedId: feedId.map(String),
      priceData: { value, timestamp, writeTimestamp: timestamp },
    },
  }),
});

const skipEvent = (feedId: number[], error: string): Event => ({
  CreatedEvent: makeCreatedEvent({
    templateId: getPackageTemplateName(PRICE_UPDATE_EVENT_TEMPLATE_NAME),
    createArgument: { feedId: feedId.map(String), isSkipped: true, error },
  }),
});

describe("parsePriceData", () => {
  it("maps BTC price ($75_000) into LastRoundDetails", () => {
    const result = parsePriceData({
      value: "75000",
      timestamp: String(BASE_TS),
      writeTimestamp: String(BASE_TS + 5_000),
    });

    expect(result).toEqual({
      lastDataPackageTimestampMS: BASE_TS,
      lastBlockTimestampMS: BASE_TS + 5_000,
      lastValue: 75_000n * 10n ** 8n,
    });
  });

  it("maps CC sub-dollar price ($0.15)", () => {
    const result = parsePriceData({
      value: "0.15",
      timestamp: String(BASE_TS),
      writeTimestamp: String(BASE_TS),
    });

    expect(result.lastValue).toBe(15_000_000n);
  });
});

describe("findNewestContract", () => {
  it("returns undefined for an empty list", () => {
    expect(findNewestContract([])).toBeUndefined();
  });

  it("picks the event with the highest priceData.timestamp", () => {
    const oldEth = makeCreatedEvent({
      contractId: CID.ethOld,
      createArgument: { priceData: { timestamp: String(BASE_TS) } },
    });
    const newEth = makeCreatedEvent({
      contractId: CID.ethNew,
      createArgument: { priceData: { timestamp: String(BASE_TS + 60_000) } },
    });

    expect(findNewestContract([oldEth, newEth])?.contractId).toBe(CID.ethNew);
  });

  it("treats missing priceData as timestamp 0", () => {
    const withTs = makeCreatedEvent({
      contractId: CID.btcFresh,
      createArgument: { priceData: { timestamp: "1" } },
    });
    const withoutTs = makeCreatedEvent({ contractId: CID.btcBlank, createArgument: {} });

    expect(findNewestContract([withoutTs, withTs])?.contractId).toBe(CID.btcFresh);
  });
});

describe("createFeedIdFilter", () => {
  it("accepts only the listed feed ids", () => {
    const filter = createFeedIdFilter([ETH_ARR]);

    expect(filter({ feedId: ETH_STR, adapterId: "a" })).toBe(true);
    expect(filter({ feedId: BTC_STR, adapterId: "a" })).toBe(false);
  });

  it("accepts multiple allowed feed ids (BTC, CC)", () => {
    const filter = createFeedIdFilter([BTC_ARR, CC_ARR]);

    expect(filter({ feedId: BTC_STR, adapterId: "a" })).toBe(true);
    expect(filter({ feedId: CC_STR, adapterId: "a" })).toBe(true);
    expect(filter({ feedId: ETH_STR, adapterId: "a" })).toBe(false);
  });

  it("also requires adapterId match when provided", () => {
    const filter = createFeedIdFilter([ETH_ARR], PRICE_ADAPTER_ID);

    expect(filter({ feedId: ETH_STR, adapterId: PRICE_ADAPTER_ID })).toBe(true);
    expect(filter({ feedId: ETH_STR, adapterId: "other" })).toBe(false);
  });

  it("ignores adapterId when none is supplied", () => {
    const filter = createFeedIdFilter([ETH_ARR]);

    expect(filter({ feedId: ETH_STR, adapterId: "anything" })).toBe(true);
  });
});

describe("createStalenessFilter", () => {
  const NOW = BASE_TS;

  beforeEach(() => {
    jest.spyOn(Date, "now").mockReturnValue(NOW);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it("keeps fresh contracts by default", () => {
    const filter = createStalenessFilter();

    expect(
      filter({ priceData: { writeTimestamp: String(NOW - 1_000) }, stalenessMs: "5000" })
    ).toBe(true);
  });

  it("drops stale contracts by default", () => {
    const filter = createStalenessFilter();

    expect(
      filter({ priceData: { writeTimestamp: String(NOW - 10_000) }, stalenessMs: "5000" })
    ).toBe(false);
  });

  it("treats age exactly equal to stalenessMs as fresh", () => {
    const filter = createStalenessFilter();

    expect(
      filter({ priceData: { writeTimestamp: String(NOW - 5_000) }, stalenessMs: "5000" })
    ).toBe(true);
  });

  it("inverts selection when keepFresh=false", () => {
    const filter = createStalenessFilter(false);

    expect(
      filter({ priceData: { writeTimestamp: String(NOW - 10_000) }, stalenessMs: "5000" })
    ).toBe(true);
    expect(
      filter({ priceData: { writeTimestamp: String(NOW - 1_000) }, stalenessMs: "5000" })
    ).toBe(false);
  });
});

describe("buildArrayifiedFeedIds", () => {
  it("builds a map keyed by the textual feed id", () => {
    const map = buildArrayifiedFeedIds(["ETH", "BTC", "CC"]);

    expect(map.get("ETH")).toEqual(ETH_ARR);
    expect(map.get("BTC")).toEqual(BTC_ARR);
    expect(map.get("CC")).toEqual(CC_ARR);
  });
});

describe("groupEventsByFeedId", () => {
  it("groups events under their textual feed id", () => {
    const eth = makeCreatedEvent({ contractId: CID.eth, createArgument: { feedId: ETH_STR } });
    const btc = makeCreatedEvent({ contractId: CID.btc, createArgument: { feedId: BTC_STR } });
    const cc = makeCreatedEvent({ contractId: CID.cc, createArgument: { feedId: CC_STR } });

    const grouped = groupEventsByFeedId(
      [eth, btc, cc],
      ["ETH", "BTC", "CC"],
      buildArrayifiedFeedIds(["ETH", "BTC", "CC"])
    );

    expect(grouped["ETH"].map((e) => e.contractId)).toEqual([CID.eth]);
    expect(grouped["BTC"].map((e) => e.contractId)).toEqual([CID.btc]);
    expect(grouped["CC"].map((e) => e.contractId)).toEqual([CID.cc]);
  });
});

describe("extractPriceEvents", () => {
  it("emits a ValueUpdate event for each price pill CreatedEvent", () => {
    const result = extractPriceEvents([
      pillEvent(ETH_ARR, "25000", String(BASE_TS)),
      pillEvent(BTC_ARR, "75000", String(BASE_TS)),
      pillEvent(CC_ARR, "0.15", String(BASE_TS)),
    ]);

    expect(result["ETH"]).toMatchObject({ name: "ValueUpdate", feedId: "ETH", value: 25_000 });
    expect(result["BTC"]).toMatchObject({ name: "ValueUpdate", feedId: "BTC", value: 75_000 });
    expect(result["CC"]).toMatchObject({ name: "ValueUpdate", feedId: "CC", value: 0.15 });
  });

  it("classifies 'Wrong timestamps' as UpdateSkipDueToDataTimestamp", () => {
    const result = extractPriceEvents([skipEvent(BTC_ARR, "Wrong timestamps of data package")]);

    expect(result["BTC"].name).toBe("UpdateSkipDueToDataTimestamp");
  });

  it("classifies 'Signer count not achieved' as UpdateSkipDueToInvalidValue", () => {
    const result = extractPriceEvents([skipEvent(CC_ARR, "Signer count not achieved")]);

    expect(result["CC"].name).toBe("UpdateSkipDueToInvalidValue");
  });

  it("falls back to UpdateSkipDueToBlockTimestamp for other skip reasons", () => {
    const result = extractPriceEvents([skipEvent(ETH_ARR, "stale block")]);

    expect(result["ETH"].name).toBe("UpdateSkipDueToBlockTimestamp");
  });

  it("ignores non-skipped PriceUpdateEvents", () => {
    const notSkipped: Event = {
      CreatedEvent: makeCreatedEvent({
        templateId: getPackageTemplateName(PRICE_UPDATE_EVENT_TEMPLATE_NAME),
        createArgument: { feedId: ETH_STR, isSkipped: false },
      }),
    };

    expect(extractPriceEvents([notSkipped])).toEqual({});
  });

  it("ignores non-create events (e.g. archives)", () => {
    const archive: Event = {
      ArchivedEvent: makeArchivedEvent({
        contractId: CID.ethOld,
        templateId: getPackageTemplateName(PRICE_PILL_TEMPLATE_NAME),
      }),
    };

    expect(extractPriceEvents([archive])).toEqual({});
  });

  it("overwrites earlier events for the same feed id", () => {
    const result = extractPriceEvents([
      pillEvent(BTC_ARR, "70000", String(BASE_TS)),
      pillEvent(BTC_ARR, "75000", String(BASE_TS + 1_000)),
    ]);

    expect(result["BTC"]).toMatchObject({ value: 75_000 });
  });
});
