import { DEFS_KEY_FEATURED_APP_RIGHT, WRITE_PRICES_CHOICE } from "../src";
import { ArchivedEvent, CreatedEvent, ExercisedEvent } from "../src/_autogenerated";
import contracts from "../src/contracts.json";
import { getArrayifiedFeedId } from "../src/utils/conversions";

export const BASE_TS = 1_700_000_000_000;

const Defs = contracts.devnet;

export const PKG_ID = Defs.core.templateId.split(":")[0];
export const PKG_NAME = "redstone-core-v12";
export const TEMPLATE_ID = Defs.core.templateId;
export const getPackageTemplateName = (name: string) => `${PKG_ID}:${name}`;

export const SIGNATORY = Defs.signatory;
export const PRICE_ADAPTER_ID = "RedStoneAdapter-v17-0.4.0";

export const ETH_ARR = getArrayifiedFeedId("ETH");
export const BTC_ARR = getArrayifiedFeedId("BTC");
export const CC_ARR = getArrayifiedFeedId("CC");

export const ETH_STR = ETH_ARR.map(String);
export const BTC_STR = BTC_ARR.map(String);
export const CC_STR = CC_ARR.map(String);

export const CID = {
  core: Defs.core.contractId,
  featured: Defs[DEFS_KEY_FEATURED_APP_RIGHT].contractId,
  eth: "0x00110000000000000000000000000000000000000000000000000000000000",
  ethOld: "0x00220000000000000000000000000000000000000000000000000000000000",
  ethNew: "0x00330000000000000000000000000000000000000000000000000000000000",
  ethOldPill: "0x00440000000000000000000000000000000000000000000000000000000000",
  ethNewPill: "0x00550000000000000000000000000000000000000000000000000000000000",
  ethPill: "0x00660000000000000000000000000000000000000000000000000000000000",
  btc: "0x00770000000000000000000000000000000000000000000000000000000000",
  btcFresh: "0x00880000000000000000000000000000000000000000000000000000000000",
  btcBlank: "0x00990000000000000000000000000000000000000000000000000000000000",
  btcResolved: "0x00aa0000000000000000000000000000000000000000000000000000000000",
  btcChoice: "0x00bb0000000000000000000000000000000000000000000000000000000000",
  cc: "0x00cc0000000000000000000000000000000000000000000000000000000000",
  ccChoice: "0x00dd0000000000000000000000000000000000000000000000000000000000",
  adapter: "0x00ee0000000000000000000000000000000000000000000000000000000000",
  generic: "0x00ff0000000000000000000000000000000000000000000000000000000000",
  exGeneric: "0x01000000000000000000000000000000000000000000000000000000000000",
} as const;

export const BLOB = {
  core: contracts.mainnet.core.createdEventBlob,
  featured: contracts.mainnet[DEFS_KEY_FEATURED_APP_RIGHT].createdEventBlob,
  eth: "CgMyLjESmgcKRQB7lipbezDbVDHe6Akegqgj8d9qx/MrMRMM+o8Oym8SKMoSEiCt2zAYGsFhnwEuG8YkPuZbovG+05TLH",
  ethNewPill:
    "CgMyLjESmgcKRQB7lipbezDbVDHe6Akegqgj8d9qx/MrMRMM+o8Oym8SKMoSEiCt2zAYGsFhnwEuG8YkPuZbovG+05TLH",
  btc: "CgMyLjESzgYKRQByQAmSWEcuEEXeKkHNj5LK+64ygkhz9ZBL4wzj/FwsTcoSEiC2xBZW+0G4FAVHR2lfc51XgBaztnj",
} as const;

export const TX_HASH = {
  eth: "0x3f4b2c1e5d3a7b8c0f1e2d3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c",
  btc: "0x7a1e2d3c4b5a697887e1d2c3b4a596877e8d9c0b1a2f3e4d5c6b7a89f0e1d2c3",
  cc: "0xcc1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a",
  generic: "0x9f4b2c1e5d3a7b8c0f1e2d3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c",
} as const;

export const makeCreatedEvent = (overrides: Partial<CreatedEvent> = {}): CreatedEvent =>
  ({
    offset: 1,
    nodeId: 1,
    contractId: CID.generic,
    templateId: TEMPLATE_ID,
    createdEventBlob: "",
    createdAt: "2026-04-22T00:00:00Z",
    packageName: PKG_NAME,
    representativePackageId: PKG_ID,
    acsDelta: true,
    ...overrides,
  }) as CreatedEvent;

export const makeExercisedEvent = (overrides: Partial<ExercisedEvent> = {}): ExercisedEvent =>
  ({
    offset: 10,
    nodeId: 10,
    contractId: CID.exGeneric,
    templateId: TEMPLATE_ID,
    choice: WRITE_PRICES_CHOICE,
    choiceArgument: {},
    consuming: false,
    lastDescendantNodeId: 20,
    exerciseResult: undefined,
    packageName: PKG_NAME,
    acsDelta: true,
    ...overrides,
  }) as ExercisedEvent;

export const makeArchivedEvent = (overrides: Partial<ArchivedEvent> = {}): ArchivedEvent => ({
  offset: 1,
  nodeId: 2,
  contractId: CID.generic,
  templateId: TEMPLATE_ID,
  packageName: PKG_NAME,
  ...overrides,
});
