import { JsGetActiveContractsResponse } from "../src/_autogenerated";
import {
  combineIntoId,
  isApiError,
  isJsActiveContract,
  isWrongContractError,
  makeActiveContractData,
  makeInterfaceFilterByParty,
} from "../src/utils/utils";
import { BLOB, CID, makeCreatedEvent, SIGNATORY } from "./test-helpers";

describe("isApiError", () => {
  it("matches errors with body.code + body.cause", () => {
    const err = Object.assign(new Error("x"), { body: { code: "NOT_FOUND", cause: "no-cid" } });

    expect(isApiError(err)).toBe(true);
  });

  it("rejects plain errors", () => {
    expect(isApiError(new Error("x"))).toBe(false);
  });

  it("rejects when body has no cause", () => {
    const err = Object.assign(new Error("x"), { body: { code: "X" } });

    expect(isApiError(err)).toBe(false);
  });

  it("rejects errors with a string body", () => {
    const err = Object.assign(new Error("x"), { body: "not an object" });

    expect(isApiError(err)).toBe(false);
  });
});

describe("isWrongContractError", () => {
  it.each([
    "CONTRACT_NOT_FOUND",
    "LOCAL_VERDICT_INACTIVE_CONTRACTS",
    "LOCAL_VERDICT_LOCKED_CONTRACTS",
  ])("matches %s message directly", (message) => {
    expect(isWrongContractError(new Error(message))).toBe(true);
  });

  it("rejects unrelated messages", () => {
    expect(isWrongContractError(new Error("something else"))).toBe(false);
  });

  it("unwraps AggregateError and finds a wrong-contract inner", () => {
    const agg = new AggregateError([new Error("noise"), new Error("CONTRACT_NOT_FOUND")]);

    expect(isWrongContractError(agg)).toBe(true);
  });

  it("returns false for AggregateError without matching inner", () => {
    expect(isWrongContractError(new AggregateError([new Error("a"), new Error("b")]))).toBe(false);
  });
});

describe("isJsActiveContract", () => {
  it("returns true when contractEntry is a JsActiveContract", () => {
    const response = {
      workflowId: "w",
      contractEntry: { JsActiveContract: {} as never },
    } as JsGetActiveContractsResponse;

    expect(isJsActiveContract(response)).toBe(true);
  });

  it("returns false for other entry variants", () => {
    const response = {
      workflowId: "w",
      contractEntry: { JsEmpty: {} },
    } as unknown as JsGetActiveContractsResponse;

    expect(isJsActiveContract(response)).toBe(false);
  });
});

describe("combineIntoId", () => {
  it("joins interfaceId and template name with ':'", () => {
    expect(combineIntoId("pkg#M:Iface", "M:Tmpl")).toBe("pkg#M:Iface:M:Tmpl");
  });
});

describe("makeInterfaceFilterByParty", () => {
  it("produces a filter keyed by partyId requesting interface views and blobs", () => {
    const filter = makeInterfaceFilterByParty("iface-prices", SIGNATORY);

    expect(filter[SIGNATORY]).toEqual({
      cumulative: [
        {
          identifierFilter: {
            InterfaceFilter: {
              value: {
                interfaceId: "iface-prices",
                includeInterfaceView: true,
                includeCreatedEventBlob: true,
              },
            },
          },
        },
      ],
    });
  });
});

describe("makeActiveContractData", () => {
  it("maps CreatedEvent + synchronizerId", () => {
    const result = makeActiveContractData(
      makeCreatedEvent({ contractId: CID.eth, createdEventBlob: BLOB.eth }),
      "sync-primary"
    );

    expect(result).toEqual({
      contractId: CID.eth,
      synchronizerId: "sync-primary",
      createdEventBlob: BLOB.eth,
    });
  });

  it("defaults synchronizerId to an empty string when omitted", () => {
    const result = makeActiveContractData(makeCreatedEvent({ createdEventBlob: BLOB.eth }));

    expect(result.synchronizerId).toBe("");
  });

  it("treats an empty createdEventBlob as undefined", () => {
    const result = makeActiveContractData(makeCreatedEvent({ createdEventBlob: "" }));

    expect(result.createdEventBlob).toBeUndefined();
  });
});
