[project]
authors = ["Łukasz Kalbarczyk"]
entry = "prices.sw"
forc-version = "0.64.0"
license = "Apache-2.0"
name = "prices"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
redstone = { git = "https://github.com/redstone-finance/redstone-fuel-sdk", tag = "testnet-0.64.0" }

[proxy]
enabled = true
